apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: suex-enginfprojects-prod
  name: backup-enginfprojects-prod
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
