apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-enginfprojects-assets-prod
  namespace: suex-enginfprojects-prod
spec:
  schedule: "30 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-enginfprojects-prod
          volumes:
          - name: script
            configMap:
              name: backup-enginfprojects-prod-script
              defaultMode: 0777
          containers:
          - command: ["/bin/bash"]
            args: ["-c", "/script/backup.sh"]
            image: ghcr.io/zugao/mc-kubectl:v0.0.1
            name: enginfprojects-assets-prod
            envFrom:
            - secretRef:
                name: enginfprojects-assets-prod-credentials
            volumeMounts:
            - mountPath: /script
              name: script
          restartPolicy: Never
      backoffLimit: 0
