# Black formatting
[tool.black]
line-length = 150
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .github
    | instance
    | logs
    | migrations
    | mongodb
    | mysql
    | nginx
    | objectstore-data
    | profile
    | profiling
    | scratch
    | venv
    | build
    | dist
  )/
'''
