apiVersion: v1
kind: ConfigMap
metadata:
  name: enginfprojects-local
  namespace: suex-enginfprojects-test
data:
  local.py: |
    import os

    from app.shared.cloud_object_store import ObjectStore

    APP_NAME = 'enginfprojects'

    PREFERRED_URL_SCHEME = 'https'

    BACKUP_IS_LIVE = True
    EMAIL_IS_LIVE = True

    OBJECT_STORAGE_ENDPOINT_URL = os.environ.get("OBJECT_STORAGE_ENDPOINT_URL")
    OBJECT_STORAGE_REGION = os.environ.get("OBJECT_STORAGE_REGION")

    _base_storage_options = {'endpoint_url': OBJECT_STORAGE_ENDPOINT_URL,
                             'region': OBJECT_STORAGE_REGION}

    OBJECT_STORAGE_ASSETS_ACCESS_KEY = os.environ.get("OBJECT_STORAGE_ASSETS_ACCESS_KEY")
    OBJECT_STORAGE_ASSETS_SECRET_KEY = os.environ.get("OBJECT_STORAGE_ASSETS_SECRET_KEY")

    _assets_storage_options = _base_storage_options | {'access_key': OBJECT_STORAGE_ASSETS_ACCESS_KEY,
                                                       'secret_key': OBJECT_STORAGE_ASSETS_SECRET_KEY}

    OBJECT_STORAGE_BACKUP_ACCESS_KEY = os.environ.get("OBJECT_STORAGE_BACKUP_ACCESS_KEY")
    OBJECT_STORAGE_BACKUP_SECRET_KEY = os.environ.get("OBJECT_STORAGE_BACKUP_SECRET_KEY")

    _backup_storage_options = _base_storage_options | {'access_key': OBJECT_STORAGE_BACKUP_ACCESS_KEY,
                                                       'secret_key': OBJECT_STORAGE_BACKUP_SECRET_KEY}

    OBJECT_STORAGE_ASSETS_URI = os.environ.get("OBJECT_STORAGE_ASSETS_URI")
    OBJECT_STORAGE_ASSETS = ObjectStore(OBJECT_STORAGE_ASSETS_URI, _assets_storage_options)

    OBJECT_STORAGE_BACKUP_URI = os.environ.get("OBJECT_STORAGE_BACKUP_URI")
    OBJECT_STORAGE_BACKUP = ObjectStore(OBJECT_STORAGE_BACKUP_URI, _backup_storage_options)

    BRANDING_LABEL = 'EngInf projects portal'
    BRANDING_LOGIN_LANDING_STRING = 'Welcome to the Engineering & Informatics projects portal'
    BRANDING_PUBLIC_LANDING_STRING = 'Welcome to the Engineering & Informatics public projects list'
    
    ENABLE_PUBLIC_BROWSER = False
