apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enginfprojects-ingress-default
  namespace: suex-enginfprojects-test
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
      - test.enginfprojects.inf.susx.ac.uk
      secretName: ingress-cert
  rules:
    - host: test.enginfprojects.inf.susx.ac.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enginfprojects
                port:
                  number: 5000
