name: "Save docker images"
description: "Prepare, build and push Docker images"
inputs:
  registry-server:
    required: true
    description: "The destination registry server for the Docker image"
  registry-namespace:
    required: true
    description: "The destination namespace for the Docker image"
  registry-username:
    required: true
    description: "The login username for the Docker registry"
  registry-token:
    required: true
    description: "The login token for the Docker registry"
  image-name:
    required: true
    description: "The Docker image name"
  input-context:
    required: true
    description: "GitHub action build context for the Dockerfile"
  input-docker-file:
    required: true
    description: "The Dockerfile location relative to the specified context"
runs:
  using: "composite"
  steps:
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry-server }}/${{ inputs.registry-namespace }}/${{ inputs.image-name }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry-server }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-token }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        context: ${{ inputs.input-context }}
        file: ${{ inputs.input-docker-file }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
