apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enginfprojects-default-worker
  namespace: suex-enginfprojects-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enginfprojects-default-worker
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
