INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (1, 'root', 'System administrator', '#ff0000', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (2, 'admin', 'Administrative user', '#ffd705', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (3, 'faculty', 'Faculty member', '#007d39', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (4, 'student', 'Student', '#53d48d', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (5, 'office', 'School Office staff', '#02ed6d', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (6, 'reports', 'Enable access to reporting features', '#5549de', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (7, 'user_approver', 'Can validate user records', '#c01bf7', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (8, 'view_email', 'View the system email log', '#555716', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (9, 'edit_tags', 'Edit some sets of project tags, eg. transferable skills', '#c5d46d', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (10, 'project_approver', 'Can validate project descriptions', '#8d06ba', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (11, 'manage_users', 'Create, edit and manage user profiles', '#ff9900', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (12, 'email', 'Send direct emails', '#f29494', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (13, 'convenor', 'Confers project convenor privileges', '#c43030', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (14, 'moderator', 'Internal moderation of project marking', '#6e70b0', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (15, 'exam_board', 'Member of an exam board', '#e8d6d6', null);
INSERT INTO mpsproject.roles (id, name, description, colour, permissions) VALUES (16, 'external_examiner', 'External examiner', '#dde4e6', null);
