"""Remove user and recipient fields from EmailLog model

Revision ID: 0148e68343ac
Revises: a01f21d05e83
Create Date: 2022-10-12 16:16:16.523708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0148e68343ac'
down_revision = 'a01f21d05e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_log_ibfk_1', 'email_log', type_='foreignkey')
    op.drop_column('email_log', 'user_id')
    op.drop_column('email_log', 'recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('recipient', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True))
    op.add_column('email_log', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('email_log_ibfk_1', 'email_log', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
