"""Remove some obsolete fields from SubmissionRecord

Revision ID: 02622b5c296a
Revises: 6ba09a6bf8c0
Create Date: 2025-07-03 15:38:39.143074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02622b5c296a'
down_revision = '6ba09a6bf8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_column('supervisor_timestamp')
        batch_op.drop_column('marker_submitted')
        batch_op.drop_column('email_to_marker')
        batch_op.drop_column('supervisor_negative')
        batch_op.drop_column('marker_timestamp')
        batch_op.drop_column('supervisor_submitted')
        batch_op.drop_column('marker_negative')
        batch_op.drop_column('marker_positive')
        batch_op.drop_column('email_to_supervisor')
        batch_op.drop_column('supervisor_positive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_positive', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('email_to_supervisor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marker_positive', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('marker_negative', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('supervisor_submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marker_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_negative', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('email_to_marker', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marker_submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supervisor_timestamp', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
