"""Add user-to-tenant association table

Revision ID: 032eece23ab2
Revises: f51a364e0359
Create Date: 2026-03-02 02:02:56.079438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032eece23ab2'
down_revision = 'f51a364e0359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_users')
    # ### end Alembic commands ###
