"""Add force_ATAS_flag and in_2026_ATAS_campaign flags to Tenant

Revision ID: 033c2bc17874
Revises: 5983ca75f3c3
Create Date: 2026-03-04 00:30:16.517736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033c2bc17874'
down_revision = '5983ca75f3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_ATAS_flag', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('in_2026_ATAS_campaign', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('in_2026_ATAS_campaign')
        batch_op.drop_column('force_ATAS_flag')

    # ### end Alembic commands ###
