"""Switch SelectingStudent.user_id to SelectingStudent.student_id (Part 1)

Revision ID: 03868463b5b2
Revises: ae1d140ed3a7
Create Date: 2018-08-15 15:32:53.777502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03868463b5b2'
down_revision = 'ae1d140ed3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selecting_students', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'selecting_students', 'student_data', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selecting_students', type_='foreignkey')
    op.drop_column('selecting_students', 'student_id')
    # ### end Alembic commands ###
