"""Remove lifetime field from AssetLifetimeMixin

Revision ID: 05094d3749b3
Revises: b8c9eb97f21a
Create Date: 2020-01-12 00:35:17.528532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05094d3749b3'
down_revision = 'b8c9eb97f21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_assets', 'lifetime')
    op.drop_column('submitted_assets', 'lifetime')
    op.drop_column('temporary_assets', 'lifetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_assets', sa.Column('lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('submitted_assets', sa.Column('lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('generated_assets', sa.Column('lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
