"""Add grade_generated_* fields to MarkingReport

Revision ID: 05ec9fa10d08
Revises: 88584d5e1cc4
Create Date: 2026-04-01 01:54:19.964182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ec9fa10d08'
down_revision = '88584d5e1cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_generated_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_generated_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['grade_generated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_generated_timestamp')
        batch_op.drop_column('grade_generated_by_id')

    # ### end Alembic commands ###
