"""Make all String fields case-sensitive for comparison

Revision ID: 07502ea5c5fa
Revises: 5f63de9abfd3
Create Date: 2018-09-24 15:41:05.213290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07502ea5c5fa'
down_revision = '5f63de9abfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backups', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('backups', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'day_of_month',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'day_of_week',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'hour',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'minute',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'month_of_year',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('celery_intervals', 'period',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=24),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'arguments',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'exchange',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'keyword_arguments',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'queue',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'routing_key',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'task',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('degree_programmes', 'abbreviation',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('degree_programmes', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('degree_types', 'abbreviation',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('degree_types', 'colour',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('degree_types', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('descriptions', 'label',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('email_log', 'body',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('email_log', 'html',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('email_log', 'recipient',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('email_log', 'subject',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'marker_comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'presentations_comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'supervisor_comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('faculty_data', 'office',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('live_projects', 'description',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('live_projects', 'keywords',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('live_projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('live_projects', 'reading',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('matching_attempts', 'celery_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('matching_attempts', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('messages', 'body',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('messages', 'title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('notifications', 'uuid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('popularity_record', 'uuid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('project_classes', 'abbreviation',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('project_classes', 'colour',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('project_classes', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('projects', 'keywords',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('research_groups', 'abbreviation',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('research_groups', 'colour',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('research_groups', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('research_groups', 'website',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('selecting_students', 'submission_IP',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.alter_column('skill_groups', 'colour',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('skill_groups', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('supervision_team', 'abbreviation',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('supervision_team', 'colour',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('supervision_team', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'))
    op.alter_column('tasks', 'message',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('tasks', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('transferable_skills', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('users', 'current_login_ip',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('users', 'last_login_ip',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'last_login_ip',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'current_login_ip',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('transferable_skills', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'message',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('supervision_team', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('supervision_team', 'colour',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('supervision_team', 'abbreviation',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('skill_groups', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('skill_groups', 'colour',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('selecting_students', 'submission_IP',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('research_groups', 'website',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('research_groups', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('research_groups', 'colour',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('research_groups', 'abbreviation',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'keywords',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('project_classes', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('project_classes', 'colour',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('project_classes', 'abbreviation',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('popularity_record', 'uuid',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('notifications', 'uuid',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('messages', 'title',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=True)
    op.alter_column('matching_attempts', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('matching_attempts', 'celery_id',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('live_projects', 'reading',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=True)
    op.alter_column('live_projects', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('live_projects', 'keywords',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('live_projects', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=True)
    op.alter_column('faculty_data', 'office',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'supervisor_comment',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'presentations_comment',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('enrollment_record', 'marker_comment',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('email_log', 'subject',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('email_log', 'recipient',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('email_log', 'html',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=True)
    op.alter_column('email_log', 'body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=True)
    op.alter_column('descriptions', 'label',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('degree_types', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('degree_types', 'colour',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('degree_types', 'abbreviation',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('degree_programmes', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('degree_programmes', 'abbreviation',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'task',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'routing_key',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'queue',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'keyword_arguments',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'exchange',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_schedules', 'arguments',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('celery_intervals', 'period',
               existing_type=sa.String(length=24),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'month_of_year',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'minute',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'hour',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'day_of_week',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('celery_crontabs', 'day_of_month',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('backups', 'filename',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('backups', 'description',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
