"""Change skill filter tables from groups to skills

Revision ID: 09035a44d2ac
Revises: 3902253da412
Create Date: 2019-03-19 02:44:13.498090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09035a44d2ac'
down_revision = '3902253da412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenor_tskill_filters',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['transferable_skills.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'skill_id')
    )
    op.create_table('sel_tskill_filters',
    sa.Column('selector_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['transferable_skills.id'], ),
    sa.PrimaryKeyConstraint('selector_id', 'skill_id')
    )
    op.drop_table('convenor_skill_filters')
    op.drop_table('sel_skill_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sel_skill_filters',
    sa.Column('selector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skill_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], name='sel_skill_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], name='sel_skill_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('selector_id', 'skill_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('convenor_skill_filters',
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skill_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['filters.id'], name='convenor_skill_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], name='convenor_skill_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('owner_id', 'skill_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('sel_tskill_filters')
    op.drop_table('convenor_tskill_filters')
    # ### end Alembic commands ###
