"""Add Turnitin similarity score fields to SubmissionRecord model

Revision ID: 095842bd0bba
Revises: 0e9805d66fc2
Create Date: 2022-05-06 22:43:18.202940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095842bd0bba'
down_revision = '0e9805d66fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('turnitin_outcome', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('submission_records', sa.Column('turnitin_score', sa.Integer(), nullable=True))
    op.add_column('submission_records', sa.Column('turnitin_web_overlap', sa.Integer(), nullable=True))
    op.add_column('submission_records', sa.Column('turnitin_publication_overlap', sa.Integer(), nullable=True))
    op.add_column('submission_records', sa.Column('turnitin_student_overlap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_records', 'turnitin_student_overlap')
    op.drop_column('submission_records', 'turnitin_publication_overlap')
    op.drop_column('submission_records', 'turnitin_web_overlap')
    op.drop_column('submission_records', 'turnitin_score')
    op.drop_column('submission_records', 'turnitin_outcome')
    # ### end Alembic commands ###
