"""Add deployed flag to ScheduleAttempt

Revision ID: 0a059a3897b5
Revises: 186412892614
Create Date: 2018-10-23 08:21:07.442172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a059a3897b5'
down_revision = '186412892614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('deployed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'deployed')
    # ### end Alembic commands ###
