"""Add 'default' field to ProjectTagGroup model

Revision ID: 0a30e6431a33
Revises: 48424d338ce4
Create Date: 2022-12-12 12:11:55.837043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a30e6431a33'
down_revision = '48424d338ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
