"""Move feedback report generation id/timestamp fields to FeedbackReport

Revision ID: 0ae19e6e5da9
Revises: 02622b5c296a
Create Date: 2025-07-03 22:07:24.951618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ae19e6e5da9'
down_revision = '02622b5c296a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['generated_id'], ['id'])

    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('submission_records_ibfk_11'), type_='foreignkey')
        batch_op.drop_column('feedback_generated_id')
        batch_op.drop_column('feedback_generated_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_generated_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('feedback_generated_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('submission_records_ibfk_11'), 'users', ['feedback_generated_id'], ['id'])

    with op.batch_alter_table('feedback_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('generated_id')

    # ### end Alembic commands ###
