"""Add flags to MatchingAttempt to treat require/forbid as hints

Revision ID: 0b27ae643728
Revises: 634c1e2ec965
Create Date: 2023-04-02 21:50:01.852282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b27ae643728'
down_revision = '634c1e2ec965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_to_encourage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('forbid_to_discourage', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        batch_op.drop_column('forbid_to_discourage')
        batch_op.drop_column('require_to_encourage')

    # ### end Alembic commands ###
