"""Add session to rooms association table

Revision ID: 0b473569c7bf
Revises: e2962698e4aa
Create Date: 2018-10-03 00:54:04.994402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b473569c7bf'
down_revision = 'e2962698e4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_to_rooms',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_to_rooms')
    # ### end Alembic commands ###
