"""Add cached academic_year property in StudentData

Revision ID: 0bdfa1ff3f9f
Revises: e30a2ac6fd71
Create Date: 2020-09-24 14:57:59.859443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdfa1ff3f9f'
down_revision = 'e30a2ac6fd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_data', sa.Column('academic_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_data', 'academic_year')
    # ### end Alembic commands ###
