"""Add show_office flag to MessageOfTheDay model

Revision ID: 0e2ffad42745
Revises: 12c4584579fb
Create Date: 2025-02-12 19:02:35.053297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2ffad42745'
down_revision = '12c4584579fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_office', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('show_office')

    # ### end Alembic commands ###
