"""Add force_base field to MatchingAttempt

Revision ID: 0e4154edab01
Revises: 158ae4eb163a
Create Date: 2019-06-05 12:07:24.883709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4154edab01'
down_revision = '158ae4eb163a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('force_base', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'force_base')
    # ### end Alembic commands ###
