"""Add linked student_id field to CanvasStudent model

Revision ID: 0e9805d66fc2
Revises: 1a33c350e3ed
Create Date: 2022-05-05 21:07:57.297028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9805d66fc2'
down_revision = '1a33c350e3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvas_student', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'canvas_student', 'student_data', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'canvas_student', type_='foreignkey')
    op.drop_column('canvas_student', 'student_id')
    # ### end Alembic commands ###
