"""Add short_name field to FHEQ_Level

Revision ID: 0ee5e23f4a85
Revises: bb695dfb6c48
Create Date: 2018-10-30 16:21:52.947586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ee5e23f4a85'
down_revision = 'bb695dfb6c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fheq_levels', sa.Column('short_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'fheq_levels', ['short_name'])
    op.drop_column('modules', 'runs_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('runs_in', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fheq_levels', type_='unique')
    op.drop_column('fheq_levels', 'short_name')
    # ### end Alembic commands ###
