"""Add tenants association table for ResearchGroup model

Revision ID: 0f5b755285ef
Revises: a0bb7d53302e
Create Date: 2026-03-03 08:50:11.390661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5b755285ef'
down_revision = 'a0bb7d53302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'tenant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_groups')
    # ### end Alembic commands ###
