"""Remove unneeded filename field from asset models

Revision ID: 10222088c23c
Revises: a75eaec38b23
Create Date: 2023-08-04 12:58:46.848418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10222088c23c'
down_revision = 'a75eaec38b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['unique_name'])
        batch_op.drop_column('filename')

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['unique_name'])
        batch_op.drop_column('filename')

    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['unique_name'])
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=True)

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=True)

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('unique_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255),
               nullable=True)

    # ### end Alembic commands ###
