"""Add mean_CATS_per_project field to MatchingAttempt

Revision ID: 11e5c4d3b45e
Revises: 148a93abcfef
Create Date: 2018-08-24 15:14:32.049061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e5c4d3b45e'
down_revision = '148a93abcfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('mean_CATS_per_project', sa.Numeric(precision=8, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'mean_CATS_per_project')
    # ### end Alembic commands ###
