"""Add index to liveproject_id in PopularityRecord

Revision ID: 12c4584579fb
Revises: 95dce27755c3
Create Date: 2024-03-27 15:35:47.978259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c4584579fb'
down_revision = '95dce27755c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popularity_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_popularity_record_liveproject_id'), ['liveproject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popularity_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_popularity_record_liveproject_id'))

    # ### end Alembic commands ###
