"""Add maximum_occupancy field to Room model

Revision ID: 136ffcf5ea54
Revises: 3d8e2c904e6c
Create Date: 2023-01-04 17:08:56.232958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136ffcf5ea54'
down_revision = '3d8e2c904e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maximum_occupancy', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('maximum_occupancy')

    # ### end Alembic commands ###
