"""Add projects list to MatchingAttempt

Revision ID: 148a93abcfef
Revises: 17e4f6557c36
Create Date: 2018-08-24 12:02:37.044885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148a93abcfef'
down_revision = '17e4f6557c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_config_projects',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matching_attempts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['live_projects.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_config_projects')
    # ### end Alembic commands ###
