"""Refine preference submission handling; add submission metadata

Revision ID: 1601b6ba816d
Revises: 8107581498d4
Create Date: 2018-07-12 20:40:30.073393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1601b6ba816d'
down_revision = '8107581498d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liveproject_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liveproject_id'], ['live_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['selecting_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('selecting_students', sa.Column('submission_IP', sa.String(length=60), nullable=True))
    op.add_column('selecting_students', sa.Column('submission_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selecting_students', 'submission_time')
    op.drop_column('selecting_students', 'submission_IP')
    op.drop_table('selections')
    # ### end Alembic commands ###
