"""Add new parameter fields to ScheduleAttempt

Revision ID: 16f584d83b13
Revises: daf38e019e32
Create Date: 2018-11-30 13:56:47.754389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f584d83b13'
down_revision = 'daf38e019e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('if_needed_cost', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('scheduling_attempts', sa.Column('levelling_tension', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'levelling_tension')
    op.drop_column('scheduling_attempts', 'if_needed_cost')
    # ### end Alembic commands ###
