"""Add optimization bias settings to MatchingAttempt

Revision ID: 17e4f6557c36
Revises: e9c05c501abb
Create Date: 2018-08-23 23:59:11.131776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e4f6557c36'
down_revision = 'e9c05c501abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('intra_group_tension', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('matching_attempts', sa.Column('levelling_bias', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('matching_attempts', sa.Column('programme_bias', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'programme_bias')
    op.drop_column('matching_attempts', 'levelling_bias')
    op.drop_column('matching_attempts', 'intra_group_tension')
    # ### end Alembic commands ###
