"""Add time limits for retention of popularity data

Revision ID: 18717199b4c4
Revises: 8fbb40a2988c
Create Date: 2018-07-16 10:06:18.539653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18717199b4c4'
down_revision = '8fbb40a2988c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('keep_daily_popularity', sa.Integer(), nullable=True))
    op.add_column('project_classes', sa.Column('keep_hourly_popularity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'keep_hourly_popularity')
    op.drop_column('project_classes', 'keep_daily_popularity')
    # ### end Alembic commands ###
