"""Migrations to support marking workflow

Revision ID: 1a1c7479a59c
Revises: cd5bc64d06c0
Create Date: 2026-04-01 13:40:12.664638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1c7479a59c'
down_revision = 'cd5bc64d06c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('submitter_report_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('report_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['submission_roles.id'], ),
    sa.ForeignKeyConstraint(['submitter_report_id'], ['submitter_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marking_report_to_responsible_supervisors',
    sa.Column('marking_report_id', sa.Integer(), nullable=False),
    sa.Column('submission_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marking_report_id'], ['marking_reports.id'], ),
    sa.ForeignKeyConstraint(['submission_role_id'], ['submission_roles.id'], ),
    sa.PrimaryKeyConstraint('marking_report_id', 'submission_role_id')
    )
    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=8, scale=3), nullable=True))

    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_tolerance', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.drop_column('out_of_tolerance')

    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.drop_column('weight')

    op.drop_table('marking_report_to_responsible_supervisors')
    op.drop_table('moderator_reports')
    # ### end Alembic commands ###
