"""Add fields to support Canvas integration with student database

Revision ID: 1a33c350e3ed
Revises: 4adbd17167ca
Create Date: 2022-05-05 13:09:50.252385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a33c350e3ed'
down_revision = '4adbd17167ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('first_name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('last_name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('canvas_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('submission_records', sa.Column('canvas_submission_available', sa.Boolean(), nullable=True))
    op.add_column('submitting_students', sa.Column('canvas_user_id', sa.Integer(), nullable=True))
    op.add_column('submitting_students', sa.Column('canvas_missing', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submitting_students', 'canvas_missing')
    op.drop_column('submitting_students', 'canvas_user_id')
    op.drop_column('submission_records', 'canvas_submission_available')
    op.drop_table('canvas_student')
    # ### end Alembic commands ###
