"""Track accepted moderator report

Revision ID: 1a7bb7d0fb83
Revises: 9a5d234fe20d
Create Date: 2026-04-03 09:21:37.188939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7bb7d0fb83'
down_revision = '9a5d234fe20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_moderator_report_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moderator_accepted_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moderator_accepted_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_submitter_report_accepted_moderator', 'moderator_reports', ['accepted_moderator_report_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(None, 'submission_roles', ['moderator_accepted_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_submitter_report_accepted_moderator', type_='foreignkey')
        batch_op.drop_column('moderator_accepted_timestamp')
        batch_op.drop_column('moderator_accepted_id')
        batch_op.drop_column('accepted_moderator_report_id')

    # ### end Alembic commands ###
