"""Switch convenor filter records to new FilterRecord model

Revision ID: 1b7d26a53909
Revises: e2256c377e32
Create Date: 2018-07-26 14:11:43.212346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b7d26a53909'
down_revision = 'e2256c377e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convenor_group_filters',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('research_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_groups.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'research_group_id')
    )
    op.create_table('convenor_skill_filters',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('skill_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'skill_group_id')
    )
    op.drop_table('conv_skill_filters')
    op.drop_table('conv_group_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conv_group_filters',
    sa.Column('config_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('research_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], name='conv_group_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_groups.id'], name='conv_group_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('config_id', 'research_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('conv_skill_filters',
    sa.Column('config_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skill_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], name='conv_skill_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], name='conv_skill_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('config_id', 'skill_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('convenor_skill_filters')
    op.drop_table('convenor_group_filters')
    op.drop_table('filters')
    # ### end Alembic commands ###
