"""Add FormattedArticle model and some derivatives

Revision ID: 1c772e8ea1de
Revises: b0387b332565
Create Date: 2020-10-08 17:19:20.037722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c772e8ea1de'
down_revision = 'b0387b332565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formatted_articles',
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('publish', sa.Boolean(), nullable=True),
    sa.Column('publish_on', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitter_convenor_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['id'], ['formatted_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitter_project_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['formatted_articles.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['submission_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitter_project_articles')
    op.drop_table('submitter_convenor_articles')
    op.drop_table('formatted_articles')
    # ### end Alembic commands ###
