"""Tag ProjectClassConfig with convenor information

Revision ID: 1e0917180157
Revises: 51b5f808477a
Create Date: 2018-06-27 11:10:01.098762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0917180157'
down_revision = '51b5f808477a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('convenor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_class_config', 'faculty_data', ['convenor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_class_config', type_='foreignkey')
    op.drop_column('project_class_config', 'convenor_id')
    # ### end Alembic commands ###
