"""Add role-based access control for all *Asset models

Revision ID: 1e2ec1026caf
Revises: 9fc696ce9400
Create Date: 2019-12-20 00:09:16.682998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2ec1026caf'
down_revision = '9fc696ce9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acr_generated',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['generated_assets.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'role_id')
    )
    op.create_table('acr_submitted',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['submitted_assets.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'role_id')
    )
    op.create_table('acr_temporary',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['temporary_assets.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acr_temporary')
    op.drop_table('acr_submitted')
    op.drop_table('acr_generated')
    # ### end Alembic commands ###
