"""Add number_marker and number_moderator fields to submission period models

Revision ID: 2049a2cc5043
Revises: 9262f8c4f1d1
Create Date: 2022-12-15 14:51:39.840248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2049a2cc5043'
down_revision = '9262f8c4f1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_markers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_moderators', sa.Integer(), nullable=True))

    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_markers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_moderators', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.drop_column('number_moderators')
        batch_op.drop_column('number_markers')

    with op.batch_alter_table('period_definitions', schema=None) as batch_op:
        batch_op.drop_column('number_moderators')
        batch_op.drop_column('number_markers')

    # ### end Alembic commands ###
