"""Refactor project class enrollment; add EnrollmentRecord model

Revision ID: 212673ccb24b
Revises: b5b6882cede1
Create Date: 2018-06-13 00:26:24.873177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212673ccb24b'
down_revision = 'b5b6882cede1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pclass_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_state', sa.Integer(), nullable=True),
    sa.Column('supervisor_comment', sa.String(length=255), nullable=True),
    sa.Column('supervisor_reenroll', sa.Integer(), nullable=True),
    sa.Column('marker_state', sa.Integer(), nullable=True),
    sa.Column('marker_comment', sa.String(length=255), nullable=True),
    sa.Column('marker_reenroll', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['pclass_id'], ['project_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('faculty_enrollments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_enrollments',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_class_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_class_id'], ['project_classes.id'], name='faculty_enrollments_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['faculty_data.id'], name='faculty_enrollments_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'project_class_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('enrollment_record')
    # ### end Alembic commands ###
