"""Add MatchingRole model

Revision ID: 22406fd8be14
Revises: 41cac4d21130
Create Date: 2022-12-18 22:43:02.260454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22406fd8be14'
down_revision = '41cac4d21130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching_to_roles',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['matching_records.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['matching_roles.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'role_id')
    )
    op.create_table('matching_to_roles_original',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['matching_records.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['matching_roles.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_to_roles_original')
    op.drop_table('matching_to_roles')
    op.drop_table('matching_roles')
    # ### end Alembic commands ###
