"""Add modules list to DegreePrograme

Revision ID: 262776866c25
Revises: d6379687d47b
Create Date: 2018-10-29 00:16:55.041320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262776866c25'
down_revision = 'd6379687d47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes_to_modules',
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['degree_programmes.id'], ),
    sa.PrimaryKeyConstraint('programme_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programmes_to_modules')
    # ### end Alembic commands ###
