"""Add colour field to Role mdoel

Revision ID: 272a2f0344b8
Revises: bdfdcdcfe5d8
Create Date: 2019-01-17 08:48:46.632714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272a2f0344b8'
down_revision = 'bdfdcdcfe5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('colour', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'colour')
    # ### end Alembic commands ###
