"""Add size fields to BackupRecord

Revision ID: 2807f2f11b0b
Revises: f22e7bf2db65
Create Date: 2018-06-03 16:41:13.532564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2807f2f11b0b'
down_revision = 'f22e7bf2db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('archive_size', sa.Integer(), nullable=True))
    op.add_column('backups', sa.Column('backup_size', sa.Integer(), nullable=True))
    op.add_column('backups', sa.Column('db_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'db_size')
    op.drop_column('backups', 'backup_size')
    op.drop_column('backups', 'archive_size')
    # ### end Alembic commands ###
