"""Add email preferences to User model

Revision ID: 281091b6901a
Revises: 94ebd7c19cc4
Create Date: 2019-01-19 10:16:36.619599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281091b6901a'
down_revision = '94ebd7c19cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_summaries', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_email', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('summary_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'summary_frequency')
    op.drop_column('users', 'last_email')
    op.drop_column('users', 'group_summaries')
    # ### end Alembic commands ###
