"""Drop non-null constraint on SupervisionEvent.template_id

Revision ID: 28254fe4944c
Revises: bbb4be9402ae
Create Date: 2026-03-14 19:31:16.110402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28254fe4944c'
down_revision = 'bbb4be9402ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
