"""Add ThumbnailAsset model and primary key links on SubmittedAsset and GeneratedAsset

Revision ID: 28f311a33c87
Revises: cd3e98669483
Create Date: 2026-03-30 10:01:15.518886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f311a33c87'
down_revision = 'cd3e98669483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('unique_name', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Boolean(), nullable=False),
    sa.Column('unattached', sa.Boolean(), nullable=False),
    sa.Column('bucket', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    with op.batch_alter_table('thumbnail_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thumbnail_assets_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_error', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('thumbnail_error_message', sa.String(length=255, collation='utf8_bin'), nullable=True))
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['thumbnail_id'], ['id'])

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_error', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('thumbnail_error_message', sa.String(length=255, collation='utf8_bin'), nullable=True))
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['thumbnail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thumbnail_error_message')
        batch_op.drop_column('thumbnail_error')
        batch_op.drop_column('thumbnail_id')

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thumbnail_error_message')
        batch_op.drop_column('thumbnail_error')
        batch_op.drop_column('thumbnail_id')

    with op.batch_alter_table('thumbnail_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thumbnail_assets_timestamp'))

    op.drop_table('thumbnail_assets')
    # ### end Alembic commands ###
