"""Remove unneded field include_marking_emails from PeriodAttachment

Revision ID: 29006d2845a9
Revises: 4f7b8c8a78f5
Create Date: 2020-05-29 19:48:05.320421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29006d2845a9'
down_revision = '4f7b8c8a78f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_attachments', 'include_marking_emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_attachments', sa.Column('include_marking_emails', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
