"""Add fields to EmailWorkflowItem to handle error conditions

Revision ID: 291e768fdf39
Revises: 234feab52264
Create Date: 2026-03-24 18:52:28.219290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291e768fdf39'
down_revision = '234feab52264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('error_condition', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.String(length=255, collation='utf8_bin'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('error_condition')
        batch_op.drop_column('send_attempts')

    # ### end Alembic commands ###
