"""Add feedback generation fields to SubmissionRecord

Revision ID: 2a204bd535f6
Revises: 65daa437bfb7
Create Date: 2025-07-02 08:55:42.683711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a204bd535f6'
down_revision = '65daa437bfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feedback_generated_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_generated_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['feedback_generated_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feedback_generated_timestamp')
        batch_op.drop_column('feedback_generated_id')
        batch_op.drop_column('feedback_generated')

    # ### end Alembic commands ###
