"""Introduce ProjectDescription model

Revision ID: 2d91da792f60
Revises: 11e5c4d3b45e
Create Date: 2018-08-27 21:06:52.277498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d91da792f60'
down_revision = '11e5c4d3b45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reading', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description_to_pclasses',
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('project_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['descriptions.id'], ),
    sa.ForeignKeyConstraint(['project_class_id'], ['project_classes.id'], ),
    sa.PrimaryKeyConstraint('description_id', 'project_class_id')
    )
    op.create_table('description_to_supervisors',
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['descriptions.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervision_team.id'], ),
    sa.PrimaryKeyConstraint('description_id', 'supervisor_id')
    )
    op.add_column('projects', sa.Column('default_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'descriptions', ['default_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'default_id')
    op.drop_table('description_to_supervisors')
    op.drop_table('description_to_pclasses')
    op.drop_table('descriptions')
    # ### end Alembic commands ###
