"""Add MatchingAttempt model

Revision ID: 2e26e0741dc1
Revises: 3a478163e6b3
Create Date: 2018-08-16 13:39:16.061468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e26e0741dc1'
down_revision = '3a478163e6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ignore_per_faculty_limits', sa.Boolean(), nullable=True),
    sa.Column('years_memory', sa.Integer(), nullable=True),
    sa.Column('supervising_limit', sa.Integer(), nullable=True),
    sa.Column('marking_limit', sa.Integer(), nullable=True),
    sa.Column('max_marking_multiplicity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['year'], ['main_config.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_matching_attempts_timestamp'), 'matching_attempts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_attempts_timestamp'), table_name='matching_attempts')
    op.drop_table('matching_attempts')
    # ### end Alembic commands ###
