"""Remove obsolete fields from Project

Revision ID: 32122565686d
Revises: 50fb65a1920f
Create Date: 2018-08-28 21:15:39.782755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32122565686d'
down_revision = '50fb65a1920f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_to_supervision')
    op.drop_column('projects', 'capacity')
    op.drop_column('projects', 'reading')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', mysql.VARCHAR(length=8000), nullable=True))
    op.add_column('projects', sa.Column('reading', mysql.VARCHAR(length=8000), nullable=True))
    op.add_column('projects', sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('project_to_supervision',
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('supervisor.id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_to_supervision_ibfk_1'),
    sa.ForeignKeyConstraint(['supervisor.id'], ['supervision_team.id'], name='project_to_supervision_ibfk_2'),
    sa.PrimaryKeyConstraint('project_id', 'supervisor.id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
