"""Add final version email timestamps to ScheduleAttempt

Revision ID: 32fae2aef615
Revises: d4e38abaf3a0
Create Date: 2019-01-28 10:34:55.400844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fae2aef615'
down_revision = 'd4e38abaf3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('final_to_assessors', sa.DateTime(), nullable=True))
    op.add_column('scheduling_attempts', sa.Column('final_to_submitters', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'final_to_submitters')
    op.drop_column('scheduling_attempts', 'final_to_assessors')
    # ### end Alembic commands ###
