"""Add presentation_list to ProjectClass model

Revision ID: 33994cfc0340
Revises: 07502ea5c5fa
Create Date: 2018-09-26 10:18:33.691387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ScalarListType


# revision identifiers, used by Alembic.
revision = '33994cfc0340'
down_revision = '07502ea5c5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('presentation_list', ScalarListType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'presentation_list')
    # ### end Alembic commands ###
