"""Add draft circulation email timestamps to ScheduleAttempt

Revision ID: 342bf3bbb8ac
Revises: aa099dd666cc
Create Date: 2018-12-14 18:08:53.372110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342bf3bbb8ac'
down_revision = 'aa099dd666cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('draft_to_assessors', sa.DateTime(), nullable=True))
    op.add_column('scheduling_attempts', sa.Column('draft_to_submitters', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'draft_to_submitters')
    op.drop_column('scheduling_attempts', 'draft_to_assessors')
    # ### end Alembic commands ###
