"""Add workflow history tables

Revision ID: 34dd50ad50c8
Revises: baf526e4a9b6
Create Date: 2019-03-16 16:36:59.705201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34dd50ad50c8'
down_revision = 'baf526e4a9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_project',
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['descriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_project_timestamp'), 'workflow_project', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workflow_project_user_id'), 'workflow_project', ['user_id'], unique=False)
    op.create_table('workflow_studentdata',
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['student_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_studentdata_timestamp'), 'workflow_studentdata', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workflow_studentdata_user_id'), 'workflow_studentdata', ['user_id'], unique=False)
    op.add_column('descriptions', sa.Column('confirmed_id', sa.Integer(), nullable=True))
    op.add_column('descriptions', sa.Column('confirmed_timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'descriptions', 'users', ['confirmed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'descriptions', type_='foreignkey')
    op.drop_column('descriptions', 'confirmed_timestamp')
    op.drop_column('descriptions', 'confirmed_id')
    op.drop_index(op.f('ix_workflow_studentdata_user_id'), table_name='workflow_studentdata')
    op.drop_index(op.f('ix_workflow_studentdata_timestamp'), table_name='workflow_studentdata')
    op.drop_table('workflow_studentdata')
    op.drop_index(op.f('ix_workflow_project_user_id'), table_name='workflow_project')
    op.drop_index(op.f('ix_workflow_project_timestamp'), table_name='workflow_project')
    op.drop_table('workflow_project')
    # ### end Alembic commands ###
