"""Change attendance comment type from String to Text

Revision ID: 34ec3df416a2
Revises: 3f5d6525d5ef
Create Date: 2018-11-28 14:48:53.997759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34ec3df416a2'
down_revision = '3f5d6525d5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessor_attendance_data', 'comment')
    op.add_column('assessor_attendance_data', sa.Column('comment', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessor_attendance_data', 'comment')
    op.add_column('assessor_attendance_data', sa.Column('comment', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
