"""Add published field to MatchingAttempt

Revision ID: 36b70f25c566
Revises: 6f61ca012db7
Create Date: 2018-09-03 13:28:19.872308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b70f25c566'
down_revision = '6f61ca012db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'published')
    # ### end Alembic commands ###
