"""Add separate Canvas module id field to SubmissionRecord

Revision ID: 382a6ef3ed36
Revises: 9d1edfa78a8d
Create Date: 2022-12-15 13:47:52.393429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a6ef3ed36'
down_revision = '9d1edfa78a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_module_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_module_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('canvas_assignment_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.drop_column('canvas_assignment_id')
        batch_op.drop_column('canvas_module_id')

    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.drop_column('canvas_module_id')

    # ### end Alembic commands ###
