"""Move number_assessors from SchedulingAttempt to PresentationAssessment

Revision ID: 387816c62942
Revises: cd667ac74a34
Create Date: 2018-10-07 23:53:41.640188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '387816c62942'
down_revision = 'cd667ac74a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_assessments', sa.Column('number_assessors', sa.Integer(), nullable=True))
    op.drop_column('scheduling_attempts', 'number_assessors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('number_assessors', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('presentation_assessments', 'number_assessors')
    # ### end Alembic commands ###
