"""Add semester field to Module

Revision ID: 38b50cfdd286
Revises: 262776866c25
Create Date: 2018-10-29 10:50:08.519032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b50cfdd286'
down_revision = '262776866c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'semester')
    # ### end Alembic commands ###
