"""Add office field to FacultyData

Revision ID: 39d866e35508
Revises: e24bfec01a20
Create Date: 2018-05-25 12:25:50.790205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d866e35508'
down_revision = 'e24bfec01a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_data', sa.Column('office', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_data', 'office')
    # ### end Alembic commands ###
