"""Add academic_year field for FHEQ_Level

Revision ID: 3a402050a55f
Revises: 8cd017524335
Create Date: 2018-10-31 22:07:32.712311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a402050a55f'
down_revision = '8cd017524335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fheq_levels', sa.Column('academic_year', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'fheq_levels', ['academic_year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fheq_levels', type_='unique')
    op.drop_column('fheq_levels', 'academic_year')
    # ### end Alembic commands ###
