"""Add resolved_by and comment fields to ConfirmRequest model

Revision ID: 3aab5c6a7063
Revises: 0e2ffad42745
Create Date: 2025-04-29 11:51:58.102518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aab5c6a7063'
down_revision = '0e2ffad42745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirm_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['resolved_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirm_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment')
        batch_op.drop_column('resolved_id')

    # ### end Alembic commands ###
