"""Add fields to FacultyData

Revision ID: 3ba3e048e3eb
Revises: 44c09bbffa23
Create Date: 2018-05-17 10:35:38.057241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba3e048e3eb'
down_revision = '44c09bbffa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_data', sa.Column('academic_title', sa.Integer(), nullable=True))
    op.add_column('faculty_data', sa.Column('use_academic_title', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_data', 'use_academic_title')
    op.drop_column('faculty_data', 'academic_title')
    # ### end Alembic commands ###
