"""add active flag to research groups

Revision ID: 3cbd304f0ed8
Revises: e492e69a937a
Create Date: 2018-05-13 12:02:01.665513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbd304f0ed8'
down_revision = 'e492e69a937a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_groups', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_groups', 'active')
    # ### end Alembic commands ###
