"""Switch to allowing small and medium thumbnails for each asset

Revision ID: 3d62662bbc56
Revises: 28f311a33c87
Create Date: 2026-03-30 11:31:18.505961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d62662bbc56'
down_revision = '28f311a33c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small_thumbnail_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medium_thumbnail_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('generated_assets_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['medium_thumbnail_id'], ['id'])
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['small_thumbnail_id'], ['id'])
        batch_op.drop_column('thumbnail_id')

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small_thumbnail_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medium_thumbnail_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('submitted_assets_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['medium_thumbnail_id'], ['id'])
        batch_op.create_foreign_key(None, 'thumbnail_assets', ['small_thumbnail_id'], ['id'])
        batch_op.drop_column('thumbnail_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('submitted_assets_ibfk_3'), 'thumbnail_assets', ['thumbnail_id'], ['id'])
        batch_op.drop_column('medium_thumbnail_id')
        batch_op.drop_column('small_thumbnail_id')

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('generated_assets_ibfk_3'), 'thumbnail_assets', ['thumbnail_id'], ['id'])
        batch_op.drop_column('medium_thumbnail_id')
        batch_op.drop_column('small_thumbnail_id')

    # ### end Alembic commands ###
