"""rename tad->uiud in Notification

Revision ID: 3dece042bc09
Revises: d20fc49430f3
Create Date: 2018-06-08 16:43:27.769411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dece042bc09'
down_revision = 'd20fc49430f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('uuid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=False)
    op.drop_index('ix_notifications_tag', table_name='notifications')
    op.drop_column('notifications', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('tag', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_notifications_tag', 'notifications', ['tag'], unique=False)
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_column('notifications', 'uuid')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
