"""Add 'uses_moderator' field to ProjectClass and ProjectClassConfig

Revision ID: 3f3bff719a54
Revises: 2049a2cc5043
Create Date: 2022-12-15 16:19:40.071750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3bff719a54'
down_revision = '2049a2cc5043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_moderator', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_moderator', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.drop_column('uses_moderator')

    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.drop_column('uses_moderator')

    # ### end Alembic commands ###
