"""Change all_assessors_in_pool from boolean to integer, to allow greater range of possibilities

Revision ID: 3f58e86945d1
Revises: ae91824a9f89
Create Date: 2023-01-09 14:39:47.896802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f58e86945d1'
down_revision = 'ae91824a9f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        batch_op.alter_column('all_assessors_in_pool',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        batch_op.alter_column('all_assessors_in_pool',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
