"""Add prompt_delay field to SubmissionRole

Revision ID: 41c8d57ee973
Revises: 28254fe4944c
Create Date: 2026-03-14 23:12:46.171364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c8d57ee973'
down_revision = '28254fe4944c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_delay', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.drop_column('prompt_delay')

    # ### end Alembic commands ###
