"""Expand SubmissionRecord fields

Revision ID: 4219c2076494
Revises: 16f7d962559f
Create Date: 2018-09-07 10:31:16.189600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4219c2076494'
down_revision = '16f7d962559f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('acknowledge_feedback', sa.Boolean(), nullable=True))
    op.add_column('submission_records', sa.Column('faculty_response', sa.Text(), nullable=True))
    op.add_column('submission_records', sa.Column('marker_submitted', sa.Boolean(), nullable=True))
    op.add_column('submission_records', sa.Column('marker_timestamp', sa.DateTime(), nullable=True))
    op.add_column('submission_records', sa.Column('selection_config_id', sa.Integer(), nullable=True))
    op.add_column('submission_records', sa.Column('supervisor_submitted', sa.Boolean(), nullable=True))
    op.add_column('submission_records', sa.Column('supervisor_timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'submission_records', 'project_class_config', ['selection_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.drop_column('submission_records', 'supervisor_timestamp')
    op.drop_column('submission_records', 'supervisor_submitted')
    op.drop_column('submission_records', 'selection_config_id')
    op.drop_column('submission_records', 'marker_timestamp')
    op.drop_column('submission_records', 'marker_submitted')
    op.drop_column('submission_records', 'faculty_response')
    op.drop_column('submission_records', 'acknowledge_feedback')
    # ### end Alembic commands ###
