"""Minor changes to FormattedArticle hierarchy

Revision ID: 4410e757e69e
Revises: 1c772e8ea1de
Create Date: 2020-10-09 11:52:04.181788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4410e757e69e'
down_revision = '1c772e8ea1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formatted_articles', sa.Column('publication_timestamp', sa.DateTime(), nullable=True))
    op.add_column('formatted_articles', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('formatted_articles', sa.Column('title', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.drop_column('formatted_articles', 'publish_on')
    op.drop_column('formatted_articles', 'publish')
    op.add_column('submitter_convenor_articles', sa.Column('period_id', sa.Integer(), nullable=True))
    op.drop_constraint('submitter_convenor_articles_ibfk_1', 'submitter_convenor_articles', type_='foreignkey')
    op.create_foreign_key(None, 'submitter_convenor_articles', 'submission_periods', ['period_id'], ['id'])
    op.drop_column('submitter_convenor_articles', 'config_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitter_convenor_articles', sa.Column('config_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submitter_convenor_articles', type_='foreignkey')
    op.create_foreign_key('submitter_convenor_articles_ibfk_1', 'submitter_convenor_articles', 'project_class_config', ['config_id'], ['id'])
    op.drop_column('submitter_convenor_articles', 'period_id')
    op.add_column('formatted_articles', sa.Column('publish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('formatted_articles', sa.Column('publish_on', mysql.DATETIME(), nullable=True))
    op.drop_column('formatted_articles', 'title')
    op.drop_column('formatted_articles', 'published')
    op.drop_column('formatted_articles', 'publication_timestamp')
    # ### end Alembic commands ###
