"""add website field to ResearchGroup

Revision ID: 44c09bbffa23
Revises: 05d47251a4cf
Create Date: 2018-05-17 01:19:51.235548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c09bbffa23'
down_revision = '05d47251a4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_groups', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_groups', 'website')
    # ### end Alembic commands ###
