"""Remove legacy fields from MatchingRecord and SubmissionRecord

Revision ID: 44da62fcf652
Revises: 4e7a1c9f3b82
Create Date: 2026-03-29 09:03:08.944467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44da62fcf652'
down_revision = '4e7a1c9f3b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('matching_records_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('matching_records_ibfk_6'), type_='foreignkey')
        batch_op.drop_column('original_marker_id')
        batch_op.drop_column('marker_id')

    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('submission_records_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('marker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('submission_records_ibfk_1'), 'faculty_data', ['marker_id'], ['id'])

    with op.batch_alter_table('matching_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_marker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('matching_records_ibfk_6'), 'faculty_data', ['original_marker_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('matching_records_ibfk_1'), 'faculty_data', ['marker_id'], ['id'])

    # ### end Alembic commands ###
