"""Add 'add_group' field to ProjectTagGroup model

Revision ID: 48424d338ce4
Revises: b18073ce44a9
Create Date: 2022-12-12 10:16:39.278227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48424d338ce4'
down_revision = 'b18073ce44a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_group', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        batch_op.drop_column('add_group')

    # ### end Alembic commands ###
