"""Add Canvas fields to MainConfig model

Revision ID: 4adbd17167ca
Revises: e5ce7fdd2147
Create Date: 2022-05-04 11:12:37.163847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adbd17167ca'
down_revision = 'e5ce7fdd2147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_config', sa.Column('canvas_url', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('main_config', sa.Column('enable_canvas_sync', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_config', 'enable_canvas_sync')
    op.drop_column('main_config', 'canvas_url')
    # ### end Alembic commands ###
