"""Add original_alternative fields to MatchingRecord

Revision ID: 4e7a1c9f3b82
Revises: 7aac7750337d
Create Date: 2026-03-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7a1c9f3b82'
down_revision = '7aac7750337d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_alternative', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('original_parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_priority', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'live_projects', ['original_parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_priority')
        batch_op.drop_column('original_parent_id')
        batch_op.drop_column('original_alternative')

    # ### end Alembic commands ###
