"""Add EmailTemplate model

Revision ID: 53f950c43eb3
Revises: 5f7c13f45ee9
Create Date: 2026-03-09 20:05:55.661647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f950c43eb3'
down_revision = '5f7c13f45ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('pclass_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pclass_id'], ['project_classes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates')
    # ### end Alembic commands ###
