"""Add SkillGroup record

Revision ID: 55b4ea7f0620
Revises: 72e335a48996
Create Date: 2018-06-17 01:18:36.843121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b4ea7f0620'
down_revision = '72e335a48996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('colour', sa.String(length=255), nullable=True),
    sa.Column('add_group', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_groups_name'), 'skill_groups', ['name'], unique=True)
    op.add_column('transferable_skills', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transferable_skills', 'skill_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferable_skills', type_='foreignkey')
    op.drop_column('transferable_skills', 'group_id')
    op.drop_index(op.f('ix_skill_groups_name'), table_name='skill_groups')
    op.drop_table('skill_groups')
    # ### end Alembic commands ###
