"""Add missing boolean flag on SubmitterAttendanceData to indicate non-attendance

Revision ID: 5634d9a5289e
Revises: 6886849ea3bc
Create Date: 2018-11-28 10:02:31.885281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5634d9a5289e'
down_revision = '6886849ea3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitter_attendance_data', sa.Column('attending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submitter_attendance_data', 'attending')
    # ### end Alembic commands ###
