"""Add association table between tenants and DegreeProgramme

Revision ID: 5983ca75f3c3
Revises: 5bc4b6e73ed3
Create Date: 2026-03-03 19:54:00.966397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5983ca75f3c3'
down_revision = '5bc4b6e73ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_to_degree_programmes',
    sa.Column('degree_programme.id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['degree_programme.id'], ['degree_programmes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('degree_programme.id', 'tenant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_to_degree_programmes')
    # ### end Alembic commands ###
