"""Add ATAS 2026 campaign flag to MainConfig

Revision ID: 5bc4b6e73ed3
Revises: 5fdb560463c3
Create Date: 2026-03-03 19:08:35.114113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc4b6e73ed3'
down_revision = '5fdb560463c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_2026_ATAS_campaign', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_config', schema=None) as batch_op:
        batch_op.drop_column('enable_2026_ATAS_campaign')

    # ### end Alembic commands ###
