"""Switch ProjectClass.year for relation to FHEQ_Level

Revision ID: 5c5aa000fbf3
Revises: 3a402050a55f
Create Date: 2018-10-31 22:18:31.221609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c5aa000fbf3'
down_revision = '3a402050a55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('start_level_id', sa.Integer(), nullable=True))
    op.drop_index('ix_project_classes_year', table_name='project_classes')
    op.create_foreign_key(None, 'project_classes', 'fheq_levels', ['start_level_id'], ['id'])
    op.drop_column('project_classes', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_classes', type_='foreignkey')
    op.create_index('ix_project_classes_year', 'project_classes', ['year'], unique=False)
    op.drop_column('project_classes', 'start_level_id')
    # ### end Alembic commands ###
