"""Add duration field to DegreeType model

Revision ID: 5d1e15e15471
Revises: b9304b3b883d
Create Date: 2019-09-08 22:38:22.497182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1e15e15471'
down_revision = 'b9304b3b883d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree_types', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degree_types', 'duration')
    # ### end Alembic commands ###
