"""Add extra fields to DescriptionComment model

Revision ID: 5e53775dd596
Revises: 6876df03bcbc
Create Date: 2019-02-26 14:15:03.168362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e53775dd596'
down_revision = '6876df03bcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('description_comments', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('description_comments', sa.Column('visibility', sa.Integer(), nullable=True))
    op.add_column('description_comments', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'description_comments', 'main_config', ['year'], ['year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'description_comments', type_='foreignkey')
    op.drop_column('description_comments', 'year')
    op.drop_column('description_comments', 'visibility')
    op.drop_column('description_comments', 'deleted')
    # ### end Alembic commands ###
