"""Add CATS data for presentations to FacultyData

Revision ID: 5f63de9abfd3
Revises: 12af90fd61eb
Create Date: 2018-09-24 12:12:27.341558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f63de9abfd3'
down_revision = '12af90fd61eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_data', sa.Column('CATS_presentation', sa.Integer(), nullable=True))
    op.alter_column('project_classes', 'number_assessors',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_classes', 'number_assessors',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('faculty_data', 'CATS_presentation')
    # ### end Alembic commands ###
