"""Update fields in SupervisionEvent record

Revision ID: 5f7c13f45ee9
Revises: 57a3c854811e
Create Date: 2026-03-06 10:34:31.092771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f7c13f45ee9'
down_revision = '57a3c854811e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('supervision_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitter_notes', sa.Text(), nullable=True))
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key(None, 'supervision_event_templates', ['template_id'], ['id'])
        batch_op.drop_column('private_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_notes', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('submitter_notes')
        batch_op.drop_column('supervision_notes')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
