"""Add BackupConfiguration

Revision ID: 6256d1a12bc3
Revises: 2807f2f11b0b
Create Date: 2018-06-04 00:27:14.463855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6256d1a12bc3'
down_revision = '2807f2f11b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keep_hourly', sa.Integer(), nullable=True),
    sa.Column('keep_daily', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_config')
    # ### end Alembic commands ###
