"""Move project validation fields into ProjectDescription

Revision ID: 674c5d6a52e3
Revises: 94ac9c6718c5
Create Date: 2019-02-24 08:03:16.218233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '674c5d6a52e3'
down_revision = '94ac9c6718c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptions', sa.Column('validated_timestamp', sa.DateTime(), nullable=True))
    op.add_column('descriptions', sa.Column('validator_id', sa.Integer(), nullable=True))
    op.add_column('descriptions', sa.Column('workflow_state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'descriptions', 'users', ['validator_id'], ['id'])
    op.drop_constraint('projects_ibfk_6', 'projects', type_='foreignkey')
    op.drop_column('projects', 'validator_id')
    op.drop_column('projects', 'validated_timestamp')
    op.drop_column('projects', 'workflow_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workflow_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('validated_timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('projects', sa.Column('validator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_ibfk_6', 'projects', 'users', ['validator_id'], ['id'])
    op.drop_constraint(None, 'descriptions', type_='foreignkey')
    op.drop_column('descriptions', 'workflow_state')
    op.drop_column('descriptions', 'validator_id')
    op.drop_column('descriptions', 'validated_timestamp')
    # ### end Alembic commands ###
