"""Track lowest-rank assigned to popularity score

Revision ID: 675dafa82779
Revises: 37066c508047
Create Date: 2018-07-17 09:43:58.302843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675dafa82779'
down_revision = '37066c508047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popularity_record', sa.Column('lowest_score_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popularity_record', 'lowest_score_rank')
    # ### end Alembic commands ###
