"""Add new, self-container Assessor and Submitter attendance data records

Revision ID: 6886849ea3bc
Revises: 689e4864420f
Create Date: 2018-11-28 09:43:11.614379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6886849ea3bc'
down_revision = '689e4864420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessor_attendance_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessor_available',
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['assessor_attendance_data.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.PrimaryKeyConstraint('assessor_id', 'session_id')
    )
    op.create_table('assessor_ifneeded',
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['assessor_attendance_data.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.PrimaryKeyConstraint('assessor_id', 'session_id')
    )
    op.create_table('assessor_unavailable',
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['assessor_attendance_data.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.PrimaryKeyConstraint('assessor_id', 'session_id')
    )
    op.create_table('submitter_attendance_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['submission_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitter_available',
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitter_attendance_data.id'], ),
    sa.PrimaryKeyConstraint('submitter_id', 'session_id')
    )
    op.create_table('submitter_unavailable',
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitter_attendance_data.id'], ),
    sa.PrimaryKeyConstraint('submitter_id', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitter_unavailable')
    op.drop_table('submitter_available')
    op.drop_table('submitter_attendance_data')
    op.drop_table('assessor_unavailable')
    op.drop_table('assessor_ifneeded')
    op.drop_table('assessor_available')
    op.drop_table('assessor_attendance_data')
    # ### end Alembic commands ###
