"""Add assessor_multiplicity_per_session field to ScheduleAttempt

Revision ID: 68ec9fd9c03e
Revises: fec63750affe
Create Date: 2023-02-02 13:26:37.221644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ec9fd9c03e'
down_revision = 'fec63750affe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessor_multiplicity_per_session', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        batch_op.drop_column('assessor_multiplicity_per_session')

    # ### end Alembic commands ###
