"""Add hand-in date field to SubmissionPeriodRecord

Revision ID: 6923193e4023
Revises: b1cd6f33ee1e
Create Date: 2020-09-29 14:13:02.625413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6923193e4023'
down_revision = 'b1cd6f33ee1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_periods', sa.Column('hand_in_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_periods', 'hand_in_date')
    # ### end Alembic commands ###
