"""Change SelectionRecord.user_id to SelectionRecord.owner_id (part 1)

Revision ID: 6b5f40d64c38
Revises: ab6ba38c6b93
Create Date: 2018-08-16 09:49:06.886465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5f40d64c38'
down_revision = 'ab6ba38c6b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'selections', 'selecting_students', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selections', type_='foreignkey')
    op.drop_column('selections', 'owner_id')
    # ### end Alembic commands ###
