"""Add feedback push fields to SubmissionRole

Revision ID: 6ba09a6bf8c0
Revises: f71a25cdd4a0
Create Date: 2025-07-03 11:14:00.320614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba09a6bf8c0'
down_revision = 'f71a25cdd4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feedback_push_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_push_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['feedback_push_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feedback_push_timestamp')
        batch_op.drop_column('feedback_push_id')
        batch_op.drop_column('feedback_sent')

    # ### end Alembic commands ###
