"""Add email status fields to AssessorAttendanceData model

Revision ID: 6d4706c00935
Revises: f7046aca3427
Create Date: 2019-12-10 00:38:51.446036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4706c00935'
down_revision = 'f7046aca3427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessor_attendance_data', sa.Column('last_reminder_timestamp', sa.DateTime(), nullable=True))
    op.add_column('assessor_attendance_data', sa.Column('reminder_email_sent', sa.Boolean(), nullable=True))
    op.add_column('assessor_attendance_data', sa.Column('request_email_sent', sa.Boolean(), nullable=True))
    op.add_column('assessor_attendance_data', sa.Column('request_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessor_attendance_data', 'request_timestamp')
    op.drop_column('assessor_attendance_data', 'request_email_sent')
    op.drop_column('assessor_attendance_data', 'reminder_email_sent')
    op.drop_column('assessor_attendance_data', 'last_reminder_timestamp')
    # ### end Alembic commands ###
