"""Change storage of PuLP outcomes in MatchingAttempt

Revision ID: 6fb5b8e3bd24
Revises: 727a405d3582
Create Date: 2018-08-21 16:34:09.097929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb5b8e3bd24'
down_revision = '727a405d3582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('outcome', sa.Integer(), nullable=True))
    op.drop_column('matching_attempts', 'success')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('matching_attempts', 'outcome')
    # ### end Alembic commands ###
