"""Add download record model for generated assets

Revision ID: 703f82159b30
Revises: 6177784bc9dc
Create Date: 2021-12-08 14:36:41.992756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703f82159b30'
down_revision = '6177784bc9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('downloader_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['generated_assets.id'], ),
    sa.ForeignKeyConstraint(['downloader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_downloads_timestamp'), 'generated_downloads', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_downloads_timestamp'), table_name='generated_downloads')
    op.drop_table('generated_downloads')
    # ### end Alembic commands ###
