"""Add flag to SubmissionPeriodDefinition to control whether feedback is collected

Revision ID: 7081d19f8047
Revises: 42e1f25579dd
Create Date: 2020-05-29 15:01:23.121819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7081d19f8047'
down_revision = '42e1f25579dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_definitions', sa.Column('collect_project_feedback', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_definitions', 'collect_project_feedback')
    # ### end Alembic commands ###
