"""Add include_only_submitted flag to MatchingAttempt

Revision ID: 71c0f796b27f
Revises: 1df13a7d6ec0
Create Date: 2019-05-15 00:48:21.123631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c0f796b27f'
down_revision = '1df13a7d6ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('include_only_submitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'include_only_submitted')
    # ### end Alembic commands ###
