"""Remove last_precompute field from User model

Revision ID: 727aa5a28800
Revises: 1058f9cd03ea
Create Date: 2024-02-14 13:53:32.233972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '727aa5a28800'
down_revision = '1058f9cd03ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_precompute')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_precompute', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
