"""Change field names in preparation for adding submission lifecycle data

Revision ID: 727a405d3582
Revises: 8133af1366ed
Create Date: 2018-08-21 11:37:36.644161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '727a405d3582'
down_revision = '8133af1366ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('feedback_open', sa.Boolean(), nullable=True))
    op.add_column('project_class_config', sa.Column('selection_closed', sa.Boolean(), nullable=True))
    op.drop_column('project_class_config', 'closed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('project_class_config', 'selection_closed')
    op.drop_column('project_class_config', 'feedback_open')
    # ### end Alembic commands ###
