"""Add email table

Revision ID: 728470f09881
Revises: 39d866e35508
Create Date: 2018-05-28 20:59:01.971184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728470f09881'
down_revision = '39d866e35508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=8000), nullable=True),
    sa.Column('html', sa.String(length=8000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_send_date'), 'email_log', ['send_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_log_send_date'), table_name='email_log')
    op.drop_table('email_log')
    # ### end Alembic commands ###
