"""Add FacultyBatch and FacultyBatchItem models

Revision ID: 72c687413d07
Revises: fee217d8bb4e
Create Date: 2026-02-25 22:42:08.230503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c687413d07'
down_revision = 'fee217d8bb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('celery_id', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('celery_finished', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('interpreted_lines', sa.Integer(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_faculty_name'), ['name'], unique=False)

    op.create_table('batch_faculty_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('existing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('first_name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('last_name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('email', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('office', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('CATS_supervision', sa.Integer(), nullable=True),
    sa.Column('CATS_marking', sa.Integer(), nullable=True),
    sa.Column('CATS_moderation', sa.Integer(), nullable=True),
    sa.Column('CATS_presentation', sa.Integer(), nullable=True),
    sa.Column('dont_convert', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['existing_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['batch_faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_faculty_items')
    with op.batch_alter_table('batch_faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_faculty_name'))

    op.drop_table('batch_faculty')
    # ### end Alembic commands ###
