"""Add start_date fields to SubmissionPeriod* models

Revision ID: 755309c41e84
Revises: 09020eacaccd
Create Date: 2019-02-19 12:44:00.983217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755309c41e84'
down_revision = '09020eacaccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_definitions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('submission_periods', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_periods', 'start_date')
    op.drop_column('period_definitions', 'start_date')
    # ### end Alembic commands ###
