"""Add unlock_date field to BackupRecord

Revision ID: 757e3fbc1e43
Revises: 74c66abd36ed
Create Date: 2024-03-07 23:18:23.679046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757e3fbc1e43'
down_revision = '74c66abd36ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_column('unlock_date')

    # ### end Alembic commands ###
