"""Add matching_config field to MainConfig

Revision ID: 76d82cdeb8e1
Revises: 2e26e0741dc1
Create Date: 2018-08-16 13:44:14.188923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d82cdeb8e1'
down_revision = '2e26e0741dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_config', sa.Column('matching_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'main_config', 'matching_attempts', ['matching_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_config', type_='foreignkey')
    op.drop_column('main_config', 'matching_id')
    # ### end Alembic commands ###
