"""Add 2nd marker fields to Project and LiveProject

Revision ID: 77000d5dd40b
Revises: f5fc7e51cce2
Create Date: 2018-08-09 16:54:15.741759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77000d5dd40b'
down_revision = 'f5fc7e51cce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_to_markers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'faculty_id')
    )
    op.create_table('live_project_to_markers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['live_projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'faculty_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_project_to_markers')
    op.drop_table('project_to_markers')
    # ### end Alembic commands ###
