"""Move confirmation fields to AssessorAttendanceData

Revision ID: 77cd62a460e2
Revises: 22f115aba470
Create Date: 2018-11-30 09:33:06.288817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cd62a460e2'
down_revision = '22f115aba470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessor_attendance_data', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('assessor_attendance_data', sa.Column('confirmed_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessor_attendance_data', 'confirmed_timestamp')
    op.drop_column('assessor_attendance_data', 'confirmed')
    # ### end Alembic commands ###
