"""Add UploadedAsset record and associate ACL

Revision ID: 77ffef80337a
Revises: ade8ca00723a
Create Date: 2018-12-06 09:20:58.694702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ffef80337a'
down_revision = 'ade8ca00723a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_assets_timestamp'), 'uploaded_assets', ['timestamp'], unique=False)
    op.create_table('acl_uploaded',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['uploaded_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acl_uploaded')
    op.drop_index(op.f('ix_uploaded_assets_timestamp'), table_name='uploaded_assets')
    op.drop_table('uploaded_assets')
    # ### end Alembic commands ###
