"""Add models to support CustomOfferHint fraemwork

Revision ID: 7aac7750337d
Revises: 8236c7055bc9
Create Date: 2026-03-28 16:32:36.508103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aac7750337d'
down_revision = '8236c7055bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_offer_hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selector_id', sa.Integer(), nullable=False),
    sa.Column('submission_record_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.ForeignKeyConstraint(['submission_record_id'], ['submission_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selector_id', 'submission_record_id', name='uq_custom_offer_hint_selector_record')
    )
    with op.batch_alter_table('custom_offer_hints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_offer_hints_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_offer_hints_selector_id'), ['selector_id'], unique=False)

    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_hints_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('offer_hints_generated_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.drop_column('offer_hints_generated_timestamp')
        batch_op.drop_column('offer_hints_generated')

    with op.batch_alter_table('custom_offer_hints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_offer_hints_selector_id'))
        batch_op.drop_index(batch_op.f('ix_custom_offer_hints_faculty_id'))

    op.drop_table('custom_offer_hints')
    # ### end Alembic commands ###
