"""Add student_engaged flag to SubmissionRecord

Revision ID: 7d5e1ea2f69d
Revises: cff0d0f90e53
Create Date: 2018-09-13 19:05:28.588653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5e1ea2f69d'
down_revision = 'cff0d0f90e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('student_engaged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_records', 'student_engaged')
    # ### end Alembic commands ###
