"""Add 'ping' and 'since' fields to 'User'

Revision ID: 7ebbd0b83c35
Revises: 5a659d3c346e
Create Date: 2019-04-01 23:57:20.545256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebbd0b83c35'
down_revision = '5a659d3c346e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ping', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('since', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'since')
    op.drop_column('users', 'ping')
    # ### end Alembic commands ###
