"""Add uses_tolerance field to MarkingScheme

Revision ID: 7fb3f39a90b3
Revises: 3f86a8fa2ca7
Create Date: 2026-03-26 01:25:04.427872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb3f39a90b3'
down_revision = '3f86a8fa2ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_marking_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_tolerance', sa.Boolean(), nullable=False))
        batch_op.alter_column('uses_standard_feedback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_tolerance', sa.Boolean(), nullable=False))
        batch_op.alter_column('uses_standard_feedback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('uses_standard_feedback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('uses_tolerance')

    with op.batch_alter_table('live_marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('uses_standard_feedback',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('uses_tolerance')

    # ### end Alembic commands ###
