"""Add ConvenorGenericTask concept

Revision ID: 7fc858dfefd2
Revises: 0c3efb48e634
Create Date: 2020-09-09 10:07:31.721884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc858dfefd2'
down_revision = '0c3efb48e634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tasks',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['tasks_id'], ['convenor_tasks.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'tasks_id')
    )
    op.add_column('convenor_tasks', sa.Column('repeat', sa.Boolean(), nullable=True))
    op.add_column('convenor_tasks', sa.Column('repeat_frequency', sa.Integer(), nullable=True))
    op.add_column('convenor_tasks', sa.Column('repeat_from_due_date', sa.Integer(), nullable=True))
    op.add_column('convenor_tasks', sa.Column('repeat_interval', sa.Boolean(), nullable=True))
    op.add_column('convenor_tasks', sa.Column('rollover', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_convenor_tasks_defer_date'), 'convenor_tasks', ['defer_date'], unique=False)
    op.create_index(op.f('ix_convenor_tasks_due_date'), 'convenor_tasks', ['due_date'], unique=False)
    op.drop_index('ix_convenor_student_tasks_defer_date', table_name='convenor_tasks')
    op.drop_index('ix_convenor_student_tasks_due_date', table_name='convenor_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_convenor_student_tasks_due_date', 'convenor_tasks', ['due_date'], unique=False)
    op.create_index('ix_convenor_student_tasks_defer_date', 'convenor_tasks', ['defer_date'], unique=False)
    op.drop_index(op.f('ix_convenor_tasks_due_date'), table_name='convenor_tasks')
    op.drop_index(op.f('ix_convenor_tasks_defer_date'), table_name='convenor_tasks')
    op.drop_column('convenor_tasks', 'rollover')
    op.drop_column('convenor_tasks', 'repeat_interval')
    op.drop_column('convenor_tasks', 'repeat_from_due_date')
    op.drop_column('convenor_tasks', 'repeat_frequency')
    op.drop_column('convenor_tasks', 'repeat')
    op.drop_table('project_tasks')
    # ### end Alembic commands ###
