"""Add fields for replacement matching email preamble text

Revision ID: 7ff0483513a2
Revises: eb7294fbdbe1
Create Date: 2019-06-11 16:52:27.146368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff0483513a2'
down_revision = 'eb7294fbdbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('email_text_draft_match_preamble', sa.Text(), nullable=True))
    op.add_column('project_classes', sa.Column('email_text_final_match_preamble', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'email_text_final_match_preamble')
    op.drop_column('project_classes', 'email_text_draft_match_preamble')
    # ### end Alembic commands ###
