"""Remove incorrect nullable=True flag from SupervisionEvent.mute

Revision ID: 806c959bdae6
Revises: e6fed1a9a06d
Create Date: 2026-03-16 00:15:36.240625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '806c959bdae6'
down_revision = 'e6fed1a9a06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.alter_column('mute',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.alter_column('mute',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
