"""Add fields to support CATS workload analysis

Revision ID: 8107581498d4
Revises: 1e0917180157
Create Date: 2018-07-12 12:23:34.747465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8107581498d4'
down_revision = '1e0917180157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('CATS_marking', sa.Integer(), nullable=True))
    op.add_column('project_class_config', sa.Column('CATS_supervision', sa.Integer(), nullable=True))
    op.add_column('project_classes', sa.Column('CATS_marking', sa.Integer(), nullable=True))
    op.add_column('project_classes', sa.Column('CATS_supervision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'CATS_supervision')
    op.drop_column('project_classes', 'CATS_marking')
    op.drop_column('project_class_config', 'CATS_supervision')
    op.drop_column('project_class_config', 'CATS_marking')
    # ### end Alembic commands ###
