"""Add Celery control fields to MatchingAttempt

Revision ID: 8133af1366ed
Revises: ef1ebcf63a39
Create Date: 2018-08-17 10:29:06.878063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8133af1366ed'
down_revision = 'ef1ebcf63a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('celery_id', sa.String(length=255), nullable=True))
    op.add_column('matching_attempts', sa.Column('finished', sa.Boolean(), nullable=True))
    op.add_column('matching_attempts', sa.Column('ignore_programme_prefs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'ignore_programme_prefs')
    op.drop_column('matching_attempts', 'finished')
    op.drop_column('matching_attempts', 'celery_id')
    # ### end Alembic commands ###
