"""Add dyspraxia and dyslexia sticker flags to StudentData model

Revision ID: 815670007591
Revises: 37f518a955b8
Create Date: 2021-12-07 00:30:40.732668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815670007591'
down_revision = '37f518a955b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_data', sa.Column('dyspraxia_sticker', sa.Boolean(), nullable=False))
    op.add_column('student_data', sa.Column('dyslexia_sticker', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_data', 'dyslexia_sticker')
    op.drop_column('student_data', 'dyspraxia_sticker')
    # ### end Alembic commands ###
