"""Add ProjectTag model class

Revision ID: 81990828a0d5
Revises: e806dbd2129e
Create Date: 2022-12-09 13:56:00.465973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81990828a0d5'
down_revision = 'e806dbd2129e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tags',
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('colour', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('degree_types', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)

    with op.batch_alter_table('fheq_levels', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('short_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)

    with op.batch_alter_table('research_groups', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)

    with op.batch_alter_table('selecting_students', schema=None) as batch_op:
        batch_op.alter_column('retired',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('submitting_students', schema=None) as batch_op:
        batch_op.alter_column('retired',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitting_students', schema=None) as batch_op:
        batch_op.alter_column('retired',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('selecting_students', schema=None) as batch_op:
        batch_op.alter_column('retired',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('research_groups', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)

    with op.batch_alter_table('fheq_levels', schema=None) as batch_op:
        batch_op.alter_column('short_name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)
        batch_op.alter_column('colour',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)

    with op.batch_alter_table('degree_types', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=256),
               existing_nullable=True)

    op.drop_table('project_tags')
    # ### end Alembic commands ###
