"""Add BackupLabel model

Revision ID: 823021d1bca4
Revises: c3437ff8d7d3
Create Date: 2023-10-10 07:42:22.003627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823021d1bca4'
down_revision = 'c3437ff8d7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('colour', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_column('locked')

    op.drop_table('backup_labels')
    # ### end Alembic commands ###
