"""Add Go Live notification table and office contact table

Revision ID: 83240f2497d5
Revises: 09035a44d2ac
Create Date: 2019-03-26 21:09:51.445245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83240f2497d5'
down_revision = '09035a44d2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golive_emails',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'user_id')
    )
    op.create_table('office_contacts',
    sa.Column('project_class_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_class_id'], ['project_classes.id'], ),
    sa.PrimaryKeyConstraint('project_class_id', 'office_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_contacts')
    op.drop_table('golive_emails')
    # ### end Alembic commands ###
