"""Capture details for presentation assessments in EnrollmentRecord

Revision ID: 83c5d02a43e4
Revises: 460e67c2e023
Create Date: 2018-09-24 09:26:53.149688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c5d02a43e4'
down_revision = '460e67c2e023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_record', sa.Column('presentations_comment', sa.String(length=255), nullable=True))
    op.add_column('enrollment_record', sa.Column('presentations_reenroll', sa.Integer(), nullable=True))
    op.add_column('enrollment_record', sa.Column('presentations_state', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_enrollment_record_presentations_state'), 'enrollment_record', ['presentations_state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_record_presentations_state'), table_name='enrollment_record')
    op.drop_column('enrollment_record', 'presentations_state')
    op.drop_column('enrollment_record', 'presentations_reenroll')
    op.drop_column('enrollment_record', 'presentations_comment')
    # ### end Alembic commands ###
