"""Add max_different_all_projects field to MatchingAttempt

Revision ID: 8516743acc42
Revises: 3b988293634e
Create Date: 2023-04-05 00:38:23.965229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8516743acc42'
down_revision = '3b988293634e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_different_all_projects', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        batch_op.drop_column('max_different_all_projects')

    # ### end Alembic commands ###
