"""add choices to ProjectClass

Revision ID: 8617f6f67718
Revises: d485cb36dd1c
Create Date: 2018-05-21 21:46:14.984310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8617f6f67718'
down_revision = 'd485cb36dd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('initial_choices', sa.Integer(), nullable=True))
    op.add_column('project_classes', sa.Column('switch_choices', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'switch_choices')
    op.drop_column('project_classes', 'initial_choices')
    # ### end Alembic commands ###
