"""Remove marking_distributed and external_marking_url from SubmissionRole

Revision ID: 88584d5e1cc4
Revises: dd40dca82868
Create Date: 2026-03-31 18:16:05.443165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88584d5e1cc4'
down_revision = 'dd40dca82868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.drop_column('external_marking_url')
        batch_op.drop_column('marking_distributed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marking_distributed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('external_marking_url', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True))

    # ### end Alembic commands ###
