"""Systematize names of indexes and constraints using MetaData object

Revision ID: 8c1ac9a49c79
Revises: f1a2b3c4d5e6
Create Date: 2026-04-15 21:57:22.313585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def _find_index_name(conn, table_name, columns):
    """Return the current name of a unique index identified by its exact column set,
    or None if no such index exists (already dropped / already renamed)."""
    col_list = ",".join(columns)
    result = conn.execute(
        sa.text(
            """
            SELECT INDEX_NAME
            FROM   information_schema.STATISTICS
            WHERE  TABLE_SCHEMA = DATABASE()
              AND  TABLE_NAME   = :table
              AND  NON_UNIQUE   = 0
            GROUP  BY INDEX_NAME
            HAVING GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') = :cols
            """
        ),
        {"table": table_name, "cols": col_list},
    ).fetchone()
    return result[0] if result else None


def _index_exists(conn, table_name, index_name):
    """Return True if a named index exists on the given table."""
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM   information_schema.STATISTICS
            WHERE  TABLE_SCHEMA = DATABASE()
              AND  TABLE_NAME   = :table
              AND  INDEX_NAME   = :index
            LIMIT  1
            """
        ),
        {"table": table_name, "index": index_name},
    ).fetchone()
    return result is not None


def _constraint_exists(conn, table_name, constraint_name):
    """Return True if a named constraint exists on the given table."""
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM   information_schema.TABLE_CONSTRAINTS
            WHERE  TABLE_SCHEMA    = DATABASE()
              AND  TABLE_NAME      = :table
              AND  CONSTRAINT_NAME = :constraint
            LIMIT  1
            """
        ),
        {"table": table_name, "constraint": constraint_name},
    ).fetchone()
    return result is not None


# revision identifiers, used by Alembic.
revision = '8c1ac9a49c79'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Discover non-portable index names before entering batch contexts.
    # 'event_id_2' is MySQL's auto-suffix for the second unique index starting with event_id;
    # the suffix depends on creation order and may differ across databases.
    idx_event_id_key = _find_index_name(conn, 'marking_workflows', ['event_id', 'key'])

    # 'project_tag_groups_pk' is a legacy non-standard name not defined in the models.
    # Query specifically for a unique index on 'name' whose name differs from the standard
    # column-named 'name' index, so the standard drop below handles the normal case cleanly.
    _ptg_row = conn.execute(sa.text(
        """
        SELECT INDEX_NAME
        FROM   information_schema.STATISTICS
        WHERE  TABLE_SCHEMA = DATABASE()
          AND  TABLE_NAME   = 'project_tag_groups'
          AND  NON_UNIQUE   = 0
          AND  INDEX_NAME  <> 'name'
        GROUP  BY INDEX_NAME
        HAVING GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') = 'name'
        """
    )).fetchone()
    idx_ptg_extra = _ptg_row[0] if _ptg_row else None

    # IMPORTANT: for every table the new unique constraint is created BEFORE the old index is
    # dropped. MySQL refuses to drop an index that is the sole support for a foreign key
    # constraint, even transiently. Creating the replacement first ensures another index is
    # always present to satisfy the FK before the old one is removed.
    #
    # Every create and drop is guarded against the current database state so the migration is
    # idempotent and safe to re-run after a partial failure.

    with op.batch_alter_table('backup_labels', schema=None) as batch_op:
        if not _constraint_exists(conn, 'backup_labels', 'uq_backup_labels_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_backup_labels_name'), ['name'])
        if _index_exists(conn, 'backup_labels', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('backups', schema=None) as batch_op:
        if not _constraint_exists(conn, 'backups', 'uq_backups_nonce'):
            batch_op.create_unique_constraint(batch_op.f('uq_backups_nonce'), ['nonce'])
        if not _constraint_exists(conn, 'backups', 'uq_backups_unique_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_backups_unique_name'), ['unique_name'])
        if _index_exists(conn, 'backups', 'ix_backups_nonce'):
            batch_op.drop_index(batch_op.f('ix_backups_nonce'))
        if _index_exists(conn, 'backups', 'unique_name'):
            batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('email_template_labels', schema=None) as batch_op:
        if not _constraint_exists(conn, 'email_template_labels', 'uq_email_template_labels_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_email_template_labels_name'), ['name'])
        if _index_exists(conn, 'email_template_labels', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('fheq_levels', schema=None) as batch_op:
        if not _constraint_exists(conn, 'fheq_levels', 'uq_fheq_levels_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_fheq_levels_name'), ['name'])
        if not _constraint_exists(conn, 'fheq_levels', 'uq_fheq_levels_numeric_level'):
            batch_op.create_unique_constraint(batch_op.f('uq_fheq_levels_numeric_level'), ['numeric_level'])
        if not _constraint_exists(conn, 'fheq_levels', 'uq_fheq_levels_short_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_fheq_levels_short_name'), ['short_name'])
        if _index_exists(conn, 'fheq_levels', 'name'):
            batch_op.drop_index(batch_op.f('name'))
        if _index_exists(conn, 'fheq_levels', 'numeric_level'):
            batch_op.drop_index(batch_op.f('numeric_level'))
        if _index_exists(conn, 'fheq_levels', 'short_name'):
            batch_op.drop_index(batch_op.f('short_name'))

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        if not _constraint_exists(conn, 'generated_assets', 'uq_generated_assets_nonce'):
            batch_op.create_unique_constraint(batch_op.f('uq_generated_assets_nonce'), ['nonce'])
        if not _constraint_exists(conn, 'generated_assets', 'uq_generated_assets_unique_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_generated_assets_unique_name'), ['unique_name'])
        if _index_exists(conn, 'generated_assets', 'ix_generated_assets_nonce'):
            batch_op.drop_index(batch_op.f('ix_generated_assets_nonce'))
        if _index_exists(conn, 'generated_assets', 'unique_name'):
            batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('marking_events', schema=None) as batch_op:
        if not _constraint_exists(conn, 'marking_events', 'uq_marking_events_period_id'):
            batch_op.create_unique_constraint(batch_op.f('uq_marking_events_period_id'), ['period_id', 'name'])
        if _index_exists(conn, 'marking_events', 'period_id'):
            batch_op.drop_index(batch_op.f('period_id'))

    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        if not _constraint_exists(conn, 'marking_schemes', 'uq_marking_schemes_pclass_id'):
            batch_op.create_unique_constraint(batch_op.f('uq_marking_schemes_pclass_id'), ['pclass_id', 'name'])
        if _index_exists(conn, 'marking_schemes', 'pclass_id'):
            batch_op.drop_index(batch_op.f('pclass_id'))

    with op.batch_alter_table('marking_workflows', schema=None) as batch_op:
        if not _constraint_exists(conn, 'marking_workflows', 'uq_marking_workflows_event_id_key'):
            batch_op.create_unique_constraint('uq_marking_workflows_event_id_key', ['event_id', 'key'])
        if not _constraint_exists(conn, 'marking_workflows', 'uq_marking_workflows_event_id_name'):
            batch_op.create_unique_constraint('uq_marking_workflows_event_id_name', ['event_id', 'name'])
        if not _constraint_exists(conn, 'marking_workflows', 'uq_marking_workflows_scheme_id'):
            batch_op.create_unique_constraint(batch_op.f('uq_marking_workflows_scheme_id'), ['scheme_id'])
        if _index_exists(conn, 'marking_workflows', 'event_id'):
            batch_op.drop_index(batch_op.f('event_id'))
        if idx_event_id_key:
            batch_op.drop_index(idx_event_id_key)
        if _index_exists(conn, 'marking_workflows', 'scheme_id'):
            batch_op.drop_index(batch_op.f('scheme_id'))

    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        if not _constraint_exists(conn, 'matching_attempts', 'uq_matching_attempts_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_matching_attempts_name'), ['name'])
        if _index_exists(conn, 'matching_attempts', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('presentation_assessments', schema=None) as batch_op:
        if not _constraint_exists(conn, 'presentation_assessments', 'uq_presentation_assessments_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_presentation_assessments_name'), ['name'])
        if _index_exists(conn, 'presentation_assessments', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        if not _constraint_exists(conn, 'project_tag_groups', 'uq_project_tag_groups_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_project_tag_groups_name'), ['name'])
        if _index_exists(conn, 'project_tag_groups', 'name'):
            batch_op.drop_index(batch_op.f('name'))
        if idx_ptg_extra:
            batch_op.drop_index(idx_ptg_extra)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        if not _constraint_exists(conn, 'roles', 'uq_roles_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])
        if _index_exists(conn, 'roles', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        if not _constraint_exists(conn, 'scheduling_attempts', 'uq_scheduling_attempts_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_scheduling_attempts_name'), ['name'])
        if not _constraint_exists(conn, 'scheduling_attempts', 'uq_scheduling_attempts_tag'):
            batch_op.create_unique_constraint(batch_op.f('uq_scheduling_attempts_tag'), ['tag'])
        if _index_exists(conn, 'scheduling_attempts', 'name'):
            batch_op.drop_index(batch_op.f('name'))
        if _index_exists(conn, 'scheduling_attempts', 'tag'):
            batch_op.drop_index(batch_op.f('tag'))

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        if not _constraint_exists(conn, 'student_data', 'uq_student_data_registration_number'):
            batch_op.create_unique_constraint(batch_op.f('uq_student_data_registration_number'), ['registration_number'])
        if _index_exists(conn, 'student_data', 'registration_number'):
            batch_op.drop_index(batch_op.f('registration_number'))

    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.alter_column('language_analysis',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        if not _constraint_exists(conn, 'submitted_assets', 'uq_submitted_assets_nonce'):
            batch_op.create_unique_constraint(batch_op.f('uq_submitted_assets_nonce'), ['nonce'])
        if not _constraint_exists(conn, 'submitted_assets', 'uq_submitted_assets_unique_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_submitted_assets_unique_name'), ['unique_name'])
        if _index_exists(conn, 'submitted_assets', 'ix_submitted_assets_nonce'):
            batch_op.drop_index(batch_op.f('ix_submitted_assets_nonce'))
        if _index_exists(conn, 'submitted_assets', 'unique_name'):
            batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('supervision_team', schema=None) as batch_op:
        if not _constraint_exists(conn, 'supervision_team', 'uq_supervision_team_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_supervision_team_name'), ['name'])
        if _index_exists(conn, 'supervision_team', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('template_tags', schema=None) as batch_op:
        if not _constraint_exists(conn, 'template_tags', 'uq_template_tags_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_template_tags_name'), ['name'])
        if _index_exists(conn, 'template_tags', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        if not _constraint_exists(conn, 'temporary_assets', 'uq_temporary_assets_nonce'):
            batch_op.create_unique_constraint(batch_op.f('uq_temporary_assets_nonce'), ['nonce'])
        if not _constraint_exists(conn, 'temporary_assets', 'uq_temporary_assets_unique_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_temporary_assets_unique_name'), ['unique_name'])
        if _index_exists(conn, 'temporary_assets', 'ix_temporary_assets_nonce'):
            batch_op.drop_index(batch_op.f('ix_temporary_assets_nonce'))
        if _index_exists(conn, 'temporary_assets', 'unique_name'):
            batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('thumbnail_assets', schema=None) as batch_op:
        if not _constraint_exists(conn, 'thumbnail_assets', 'uq_thumbnail_assets_unique_name'):
            batch_op.create_unique_constraint(batch_op.f('uq_thumbnail_assets_unique_name'), ['unique_name'])
        if _index_exists(conn, 'thumbnail_assets', 'unique_name'):
            batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        if not _constraint_exists(conn, 'users', 'uq_users_fs_uniquifier'):
            batch_op.create_unique_constraint(batch_op.f('uq_users_fs_uniquifier'), ['fs_uniquifier'])
        if not _constraint_exists(conn, 'users', 'uq_users_fs_webauthn_user_handle'):
            batch_op.create_unique_constraint(batch_op.f('uq_users_fs_webauthn_user_handle'), ['fs_webauthn_user_handle'])
        if _index_exists(conn, 'users', 'fs_uniquifier'):
            batch_op.drop_index(batch_op.f('fs_uniquifier'))
        if _index_exists(conn, 'users', 'fs_webauthn_user_handle'):
            batch_op.drop_index(batch_op.f('fs_webauthn_user_handle'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: the downgrade recreates 'event_id_2' and 'project_tag_groups_pk' as literal names.
    # These names are MySQL auto-generated and may not have existed on all databases before
    # the upgrade ran. Downgrade restores an unnamed state; the exact names are not load-bearing.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_fs_webauthn_user_handle'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_fs_uniquifier'), type_='unique')
        batch_op.create_index(batch_op.f('fs_webauthn_user_handle'), ['fs_webauthn_user_handle'], unique=True)
        batch_op.create_index(batch_op.f('fs_uniquifier'), ['fs_uniquifier'], unique=True)

    with op.batch_alter_table('thumbnail_assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_thumbnail_assets_unique_name'), type_='unique')
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)

    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_temporary_assets_unique_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_temporary_assets_nonce'), type_='unique')
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_temporary_assets_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('template_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_template_tags_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('supervision_team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_supervision_team_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_submitted_assets_unique_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_submitted_assets_nonce'), type_='unique')
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_submitted_assets_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.alter_column('language_analysis',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_data_registration_number'), type_='unique')
        batch_op.create_index(batch_op.f('registration_number'), ['registration_number'], unique=True)

    with op.batch_alter_table('scheduling_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_scheduling_attempts_tag'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_scheduling_attempts_name'), type_='unique')
        batch_op.create_index(batch_op.f('tag'), ['tag'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('project_tag_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_project_tag_groups_name'), type_='unique')
        batch_op.create_index(batch_op.f('project_tag_groups_pk'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('presentation_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_presentation_assessments_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('matching_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_matching_attempts_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('marking_workflows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_marking_workflows_scheme_id'), type_='unique')
        batch_op.drop_constraint('uq_marking_workflows_event_id_name', type_='unique')
        batch_op.drop_constraint('uq_marking_workflows_event_id_key', type_='unique')
        batch_op.create_index(batch_op.f('scheme_id'), ['scheme_id'], unique=True)
        batch_op.create_index(batch_op.f('event_id_2'), ['event_id', 'key'], unique=True)
        batch_op.create_index(batch_op.f('event_id'), ['event_id', 'name'], unique=True)

    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_marking_schemes_pclass_id'), type_='unique')
        batch_op.create_index(batch_op.f('pclass_id'), ['pclass_id', 'name'], unique=True)

    with op.batch_alter_table('marking_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_marking_events_period_id'), type_='unique')
        batch_op.create_index(batch_op.f('period_id'), ['period_id', 'name'], unique=True)

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_generated_assets_unique_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_generated_assets_nonce'), type_='unique')
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_generated_assets_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('fheq_levels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fheq_levels_short_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_fheq_levels_numeric_level'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_fheq_levels_name'), type_='unique')
        batch_op.create_index(batch_op.f('short_name'), ['short_name'], unique=True)
        batch_op.create_index(batch_op.f('numeric_level'), ['numeric_level'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('email_template_labels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_email_template_labels_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_backups_unique_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_backups_nonce'), type_='unique')
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_backups_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('backup_labels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_backup_labels_name'), type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
