"""Switch SelectingStudent.user_id to SelectingStudent.student_id (Part 2)

Revision ID: 8d15791770dd
Revises: 03868463b5b2
Create Date: 2018-08-15 15:33:54.036523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d15791770dd'
down_revision = '03868463b5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('selecting_students_ibfk_2', 'selecting_students', type_='foreignkey')
    op.drop_column('selecting_students', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selecting_students', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('selecting_students_ibfk_2', 'selecting_students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
