"""Remove submission_period field from SubmissionRecord

Revision ID: 8ef76755b555
Revises: 9d9e495b540c
Create Date: 2018-10-23 14:31:33.862942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ef76755b555'
down_revision = '9d9e495b540c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_records_submission_period', table_name='submission_records')
    op.drop_column('submission_records', 'submission_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('submission_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_submission_records_submission_period', 'submission_records', ['submission_period'], unique=False)
    # ### end Alembic commands ###
