"""Add popularity controls to Project, LiveProject

Revision ID: 8fbb40a2988c
Revises: 3f6e046a4d15
Create Date: 2018-07-13 19:46:23.884509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbb40a2988c'
down_revision = '3f6e046a4d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_projects', sa.Column('show_bookmarks', sa.Boolean(), nullable=True))
    op.add_column('live_projects', sa.Column('show_popularity', sa.Boolean(), nullable=True))
    op.add_column('live_projects', sa.Column('show_selections', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('show_bookmarks', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('show_popularity', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('show_selections', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'show_selections')
    op.drop_column('projects', 'show_popularity')
    op.drop_column('projects', 'show_bookmarks')
    op.drop_column('live_projects', 'show_selections')
    op.drop_column('live_projects', 'show_popularity')
    op.drop_column('live_projects', 'show_bookmarks')
    # ### end Alembic commands ###
