"""Remove 'canvas_id' fields from ProjectClassConfig and SubmissionPeriod

Revision ID: 9262f8c4f1d1
Revises: 382a6ef3ed36
Create Date: 2022-12-15 14:07:25.265398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9262f8c4f1d1'
down_revision = '382a6ef3ed36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.drop_column('canvas_id')

    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.drop_column('canvas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('project_class_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
