"""Add number_markers and number_moderators fields to ProjectClass

Revision ID: 935c8320c647
Revises: 2d170d1f440d
Create Date: 2023-03-28 22:49:25.082165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935c8320c647'
down_revision = '2d170d1f440d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_markers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_moderators', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.drop_column('number_moderators')
        batch_op.drop_column('number_markers')

    # ### end Alembic commands ###
