"""Add validation workflow fields to Project model

Revision ID: 94ac9c6718c5
Revises: 755309c41e84
Create Date: 2019-02-23 23:15:01.723594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ac9c6718c5'
down_revision = '755309c41e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('validated_timestamp', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('validator_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('workflow_state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['validator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'workflow_state')
    op.drop_column('projects', 'validator_id')
    op.drop_column('projects', 'validated_timestamp')
    # ### end Alembic commands ###
