"""Add comment field to CustomOffer model

Revision ID: 95dce27755c3
Revises: fedaa60cd053
Create Date: 2024-03-21 22:35:20.362490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dce27755c3'
down_revision = 'fedaa60cd053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_offers', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
