"""Add string recipients field to EmailLog

Revision ID: 96831a477ec1
Revises: 57b72f76d9de
Create Date: 2018-05-31 16:22:12.613241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96831a477ec1'
down_revision = '57b72f76d9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('recipient', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'recipient')
    # ### end Alembic commands ###
