"""Rename marker tables

Revision ID: 96ea0e043e64
Revises: edb57c08b0b0
Create Date: 2018-09-24 10:11:16.848300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ea0e043e64'
down_revision = 'edb57c08b0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('live_project_to_markers', 'live_project_to_assessors')
    op.rename_table('project_to_markers', 'project_to_assessors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('live_project_to_assessors', 'live_project_to_markers')
    op.rename_table('project_to_assessors', 'project_to_markers')
    # ### end Alembic commands ###
