"""Add SubmittedAsset model and infrastructure for attaching submitted files to SubmissionRecord

Revision ID: 977544ec2513
Revises: 7967c4e9136f
Create Date: 2019-12-17 15:39:46.626647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977544ec2513'
down_revision = '7967c4e9136f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_submitted',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['temporary_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'user_id')
    )
    op.create_table('submitted_assets',
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), ),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('uploaded_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['submitted_assets.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['submission_records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submitted_assets_timestamp'), 'submitted_assets', ['timestamp'], unique=False)
    op.add_column('submission_records', sa.Column('report_exemplar', sa.Boolean(), nullable=True))
    op.add_column('submission_records', sa.Column('report_id', sa.Integer(), nullable=True))
    op.add_column('submission_records', sa.Column('report_timestamp', sa.DateTime(), nullable=True))
    op.add_column('submission_records', sa.Column('report_uploaded_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission_records', 'submitted_assets', ['report_id'], ['id'])
    op.create_foreign_key(None, 'submission_records', 'users', ['report_uploaded_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.drop_column('submission_records', 'report_uploaded_id')
    op.drop_column('submission_records', 'report_timestamp')
    op.drop_column('submission_records', 'report_id')
    op.drop_column('submission_records', 'report_exemplar')
    op.drop_index(op.f('ix_submitted_assets_timestamp'), table_name='submitted_assets')
    op.drop_table('submitted_assets')
    op.drop_table('submission_attachments')
    op.drop_table('acl_submitted')
    # ### end Alembic commands ###
