"""Add active flag to EmailTemplate

Revision ID: 9780ff46fbf2
Revises: b4da2ffbe5b3
Create Date: 2026-03-09 21:20:36.791357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9780ff46fbf2'
down_revision = 'b4da2ffbe5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
