"""Add max_attachment_size field to EmailWorkflow

Revision ID: 9ba9c1b9885d
Revises: 291e768fdf39
Create Date: 2026-03-24 19:29:11.064410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba9c1b9885d'
down_revision = '291e768fdf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflow_item_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True))

    with op.batch_alter_table('email_workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attachment_size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflows', schema=None) as batch_op:
        batch_op.drop_column('max_attachment_size')

    with op.batch_alter_table('email_workflow_item_attachments', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
