"""Remove unique flag from exam number and registration number in batch import

Revision ID: 9bbbc803fec3
Revises: a3b39cba24a7
Create Date: 2021-09-27 11:11:51.191997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbbc803fec3'
down_revision = 'a3b39cba24a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('exam_number', table_name='batch_student_items')
    op.drop_index('registration_number', table_name='batch_student_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('registration_number', 'batch_student_items', ['registration_number'], unique=False)
    op.create_index('exam_number', 'batch_student_items', ['exam_number'], unique=False)
    # ### end Alembic commands ###
