"""Add schedule_slot field to SubmissionRole

Revision ID: 9d280f11b3b3
Revises: b3413f795e72
Create Date: 2026-03-24 01:30:31.782367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d280f11b3b3'
down_revision = 'b3413f795e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_slot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schedule_slots', ['schedule_slot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_slot_id')

    # ### end Alembic commands ###
