"""Add new fields to StudentBatch model

Revision ID: 9d97052e3ee1
Revises: a0ae431e27dc
Create Date: 2023-09-07 09:55:30.364008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d97052e3ee1'
down_revision = 'a0ae431e27dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('report')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
