"""Add SubmissionPeriodRecord relation to SubmissionRecord

Revision ID: 9d9e495b540c
Revises: fdfb22e562af
Create Date: 2018-10-23 12:37:04.978342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9e495b540c'
down_revision = 'fdfb22e562af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('period_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission_records', 'submission_periods', ['period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.drop_column('submission_records', 'period_id')
    # ### end Alembic commands ###
