"""Add ConfirmRequest model

Revision ID: 9fb6ea439420
Revises: ac26a80fbccb
Create Date: 2019-01-18 12:55:08.035730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb6ea439420'
down_revision = 'ac26a80fbccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('decline_justifcation', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['selecting_students.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['live_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirm_requests')
    # ### end Alembic commands ###
