"""Add multiple recipients list to EmailLog model

Revision ID: a01f21d05e83
Revises: a09da8c50fd4
Create Date: 2022-10-12 15:20:01.057449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01f21d05e83'
down_revision = 'a09da8c50fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log_recipients',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email_log.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'recipient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_log_recipients')
    # ### end Alembic commands ###
