"""Add fields to ProjectClassConfig to support accommodation of matches

Revision ID: a03d144aaa94
Revises: 4a2bfe9f6eae
Create Date: 2020-05-14 17:08:08.412500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03d144aaa94'
down_revision = '4a2bfe9f6eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('accommodate_matching_id', sa.Integer(), nullable=True))
    op.add_column('project_class_config', sa.Column('full_CATS', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_class_config', 'matching_attempts', ['accommodate_matching_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_class_config', type_='foreignkey')
    op.drop_column('project_class_config', 'full_CATS')
    op.drop_column('project_class_config', 'accommodate_matching_id')
    # ### end Alembic commands ###
