"""Updates models for Flask-Security-Too 5.0 changes

Revision ID: a09da8c50fd4
Revises: 095842bd0bba
Create Date: 2022-10-12 12:49:28.461523

"""
from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = 'a09da8c50fd4'
down_revision = '095842bd0bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True))
    op.add_column('users', sa.Column('fs_webauthn_user_handle', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['fs_webauthn_user_handle'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fs_webauthn_user_handle')
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
