"""Add tenant field to ProjectClass and ATAS_requirement fields

Revision ID: a0bb7d53302e
Revises: d98a8a13fa00
Create Date: 2026-03-03 01:44:07.348744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bb7d53302e'
down_revision = 'd98a8a13fa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ATAS_restricted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_classes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ATAS_restricted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ATAS_restricted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_column('ATAS_restricted')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('ATAS_restricted')

    with op.batch_alter_table('project_classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_classes_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('live_projects', schema=None) as batch_op:
        batch_op.drop_column('ATAS_restricted')

    # ### end Alembic commands ###
