"""Convert exam_number field in StudentData to encrypted

Revision ID: a1be1524862d
Revises: d29f9c6b3336
Create Date: 2021-12-08 09:49:03.474572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'a1be1524862d'
down_revision = 'd29f9c6b3336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_data_exam_number', table_name='student_data')
    op.drop_column('student_data', 'exam_number')

    op.add_column('student_data', sa.Column('exam_number', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_data', 'exam_number')

    op.add_column('student_data', sa.Column('exam_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_student_data_exam_number', 'student_data', ['exam_number'], unique=False)
    # ### end Alembic commands ###
