"""Add email and type flags to SubmissionRecord

Revision ID: a279e49bc4d8
Revises: 428eea9fbcc6
Create Date: 2021-01-06 14:27:06.128464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a279e49bc4d8'
down_revision = '428eea9fbcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_attachments', sa.Column('include_marker_emails', sa.Boolean(), nullable=True))
    op.add_column('submission_attachments', sa.Column('include_supervisor_emails', sa.Boolean(), nullable=True))
    op.add_column('submission_attachments', sa.Column('publish_to_students', sa.Boolean(), nullable=True))
    op.add_column('submission_attachments', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_attachments', 'type')
    op.drop_column('submission_attachments', 'publish_to_students')
    op.drop_column('submission_attachments', 'include_supervisor_emails')
    op.drop_column('submission_attachments', 'include_marker_emails')
    # ### end Alembic commands ###
