"""Fix missing table name on ConvenorSubmitterTask

Revision ID: a3b39cba24a7
Revises: a8cbbc5efcee
Create Date: 2021-09-15 14:38:19.251642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3b39cba24a7'
down_revision = 'a8cbbc5efcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenor_submitter_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['convenor_tasks.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['submitting_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('convenor_submitter_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenor_submitter_task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['convenor_tasks.id'], name='convenor_submitter_task_ibfk_1'),
    sa.ForeignKeyConstraint(['owner_id'], ['submitting_students.id'], name='convenor_submitter_task_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('convenor_submitter_tasks')
    # ### end Alembic commands ###
