"""Add hidden flag to LiveProject

Revision ID: a596251adb7d
Revises: a279e49bc4d8
Create Date: 2021-02-26 21:21:19.706054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a596251adb7d'
down_revision = 'a279e49bc4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_projects', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_projects', 'hidden')
    # ### end Alembic commands ###
