"""Add publish flag to ProjectClass

Revision ID: a6352d3d438c
Revises: d9e47af5be07
Create Date: 2019-01-29 12:58:15.789690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6352d3d438c'
down_revision = 'd9e47af5be07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('publish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'publish')
    # ### end Alembic commands ###
