"""Add database fields to support detection of stale TaskRecords

Revision ID: a6e87998550d
Revises: 9eb2cf360d38
Create Date: 2026-04-04 22:33:58.788879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e87998550d'
down_revision = '9eb2cf360d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
