"""Modify MatchingAttempt model

Revision ID: a789484f9920
Revises: e04042800bc6
Create Date: 2018-09-03 10:09:49.567060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a789484f9920'
down_revision = 'e04042800bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('creation_timestamp', sa.DateTime(), nullable=True))
    op.add_column('matching_attempts', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('matching_attempts', sa.Column('last_edit_id', sa.Integer(), nullable=True))
    op.add_column('matching_attempts', sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True))
    op.add_column('matching_attempts', sa.Column('solver', sa.Integer(), nullable=True))
    op.drop_index('ix_matching_attempts_timestamp', table_name='matching_attempts')
    op.drop_constraint('matching_attempts_ibfk_1', 'matching_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'matching_attempts', 'users', ['last_edit_id'], ['id'])
    op.create_foreign_key(None, 'matching_attempts', 'users', ['creator_id'], ['id'])
    op.drop_column('matching_attempts', 'owner_id')
    op.drop_column('matching_attempts', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('matching_attempts', sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matching_attempts', type_='foreignkey')
    op.drop_constraint(None, 'matching_attempts', type_='foreignkey')
    op.create_foreign_key('matching_attempts_ibfk_1', 'matching_attempts', 'users', ['owner_id'], ['id'])
    op.create_index('ix_matching_attempts_timestamp', 'matching_attempts', ['timestamp'], unique=False)
    op.drop_column('matching_attempts', 'solver')
    op.drop_column('matching_attempts', 'last_edit_timestamp')
    op.drop_column('matching_attempts', 'last_edit_id')
    op.drop_column('matching_attempts', 'creator_id')
    op.drop_column('matching_attempts', 'creation_timestamp')
    # ### end Alembic commands ###
