"""Add ConvenorTask model and infrastructure

Revision ID: a7ca04b7860d
Revises: b5096fd9a39d
Create Date: 2020-08-28 15:01:25.166632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ca04b7860d'
down_revision = 'b5096fd9a39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenor_tasks',
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('blocking', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('dropped', sa.Boolean(), nullable=True),
    sa.Column('defer_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convenor_tasks_defer_date'), 'convenor_tasks', ['defer_date'], unique=False)
    op.create_index(op.f('ix_convenor_tasks_due_date'), 'convenor_tasks', ['due_date'], unique=False)
    op.create_table('selector_tasks',
    sa.Column('selector_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.ForeignKeyConstraint(['tasks_id'], ['convenor_student_tasks.id'], ),
    sa.PrimaryKeyConstraint('selector_id', 'tasks_id')
    )
    op.create_table('submitter_tasks',
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitting_students.id'], ),
    sa.ForeignKeyConstraint(['tasks_id'], ['convenor_student_tasks.id'], ),
    sa.PrimaryKeyConstraint('submitter_id', 'tasks_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitter_tasks')
    op.drop_table('selector_tasks')
    op.drop_index(op.f('ix_convenor_tasks_due_date'), table_name='convenor_tasks')
    op.drop_index(op.f('ix_convenor_tasks_defer_date'), table_name='convenor_tasks')
    op.drop_table('convenor_tasks')
    # ### end Alembic commands ###
