"""add missing project description field

Revision ID: a7fb8300accf
Revises: 256a1e7bcd5d
Create Date: 2018-05-15 10:44:12.547494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fb8300accf'
down_revision = '256a1e7bcd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=8000), nullable=True))
    op.add_column('projects', sa.Column('reading', sa.String(length=8000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'reading')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
