"""Add morning/afternoon sesion definitions, and talk format fields

Revision ID: aa099dd666cc
Revises: e76a30bc87a6
Create Date: 2018-12-14 13:05:50.127247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa099dd666cc'
down_revision = 'e76a30bc87a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_definitions', sa.Column('afternoon_session', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('period_definitions', sa.Column('morning_session', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('period_definitions', sa.Column('talk_format', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('submission_periods', sa.Column('afternoon_session', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('submission_periods', sa.Column('morning_session', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.add_column('submission_periods', sa.Column('talk_format', sa.String(length=255, collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_periods', 'talk_format')
    op.drop_column('submission_periods', 'morning_session')
    op.drop_column('submission_periods', 'afternoon_session')
    op.drop_column('period_definitions', 'talk_format')
    op.drop_column('period_definitions', 'morning_session')
    op.drop_column('period_definitions', 'afternoon_session')
    # ### end Alembic commands ###
