"""Switch SubmittingStudent.user_id to SubmittingStudent.student_id

Revision ID: ab6ba38c6b93
Revises: 8d15791770dd
Create Date: 2018-08-15 15:37:23.935877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab6ba38c6b93'
down_revision = '8d15791770dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitting_students', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_constraint('submitting_students_ibfk_2', 'submitting_students', type_='foreignkey')
    op.create_foreign_key(None, 'submitting_students', 'student_data', ['student_id'], ['id'])
    op.drop_column('submitting_students', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitting_students', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submitting_students', type_='foreignkey')
    op.create_foreign_key('submitting_students_ibfk_2', 'submitting_students', 'users', ['user_id'], ['id'])
    op.drop_column('submitting_students', 'student_id')
    # ### end Alembic commands ###
