"""remove incorrect UNIQUE constraint from StudentData.cohort

Revision ID: acf3d3071d10
Revises: 2c8960d90723
Create Date: 2018-05-18 20:42:39.332391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf3d3071d10'
down_revision = '2c8960d90723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_data_cohort', table_name='student_data')
    op.create_index(op.f('ix_student_data_cohort'), 'student_data', ['cohort'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_data_cohort'), table_name='student_data')
    op.create_index('ix_student_data_cohort', 'student_data', ['cohort'], unique=1)
    # ### end Alembic commands ###
