"""Add celery_finished flag to PuLP mixing

Revision ID: ade8ca00723a
Revises: c75bb1c72b40
Create Date: 2018-12-05 22:10:05.392442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade8ca00723a'
down_revision = 'c75bb1c72b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('celery_finished', sa.Boolean(), nullable=True))
    op.add_column('scheduling_attempts', sa.Column('celery_finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'celery_finished')
    op.drop_column('matching_attempts', 'celery_finished')
    # ### end Alembic commands ###
