"""Add flag to indicate whether a ProjectClass instance uses 2nd markers

Revision ID: ae1d140ed3a7
Revises: a0d86b97c2ff
Create Date: 2018-08-10 20:36:23.988355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d140ed3a7'
down_revision = 'a0d86b97c2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('uses_marker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'uses_marker')
    # ### end Alembic commands ###
