"""Add default license field to User model

Revision ID: af1f7da8b1e8
Revises: ed2d0bf7a9f5
Create Date: 2020-01-02 12:51:01.764436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1f7da8b1e8'
down_revision = 'ed2d0bf7a9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_license_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'asset_licenses', ['default_license_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_license_id')
    # ### end Alembic commands ###
