"""Add description field to DownloadCentreItem

Revision ID: b11da9f0719f
Revises: 72c687413d07
Create Date: 2026-02-26 23:21:19.271911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11da9f0719f'
down_revision = '72c687413d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_centre_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255, collation='utf8_bin'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_centre_item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
