"""Add lp_file_id and mps_file_id fields to PulpMixin

Revision ID: b18ca484142d
Revises: 05094d3749b3
Create Date: 2020-01-15 23:48:05.455611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18ca484142d'
down_revision = '05094d3749b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('lp_file_id', sa.Integer(), nullable=True))
    op.add_column('matching_attempts', sa.Column('mps_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matching_attempts', 'generated_assets', ['mps_file_id'], ['id'])
    op.create_foreign_key(None, 'matching_attempts', 'generated_assets', ['lp_file_id'], ['id'])
    op.add_column('scheduling_attempts', sa.Column('lp_file_id', sa.Integer(), nullable=True))
    op.add_column('scheduling_attempts', sa.Column('mps_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduling_attempts', 'generated_assets', ['mps_file_id'], ['id'])
    op.create_foreign_key(None, 'scheduling_attempts', 'generated_assets', ['lp_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduling_attempts', type_='foreignkey')
    op.drop_constraint(None, 'scheduling_attempts', type_='foreignkey')
    op.drop_column('scheduling_attempts', 'mps_file_id')
    op.drop_column('scheduling_attempts', 'lp_file_id')
    op.drop_constraint(None, 'matching_attempts', type_='foreignkey')
    op.drop_constraint(None, 'matching_attempts', type_='foreignkey')
    op.drop_column('matching_attempts', 'mps_file_id')
    op.drop_column('matching_attempts', 'lp_file_id')
    # ### end Alembic commands ###
