"""Revert FeedbackAsset and ProjectAsset models

Revision ID: b46abfa5ef3a
Revises: 77177a5f44d8
Create Date: 2025-06-30 20:53:41.656471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b46abfa5ef3a'
down_revision = '77177a5f44d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_downloads_timestamp'))

    with op.batch_alter_table('project_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_assets_timestamp'))
        batch_op.drop_index(batch_op.f('nonce'))
        batch_op.drop_index(batch_op.f('unique_name'))

    with op.batch_alter_table('project_downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_downloads_timestamp'))

    with op.batch_alter_table('feedback_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_assets_timestamp'))
        batch_op.drop_index(batch_op.f('nonce'))
        batch_op.drop_index(batch_op.f('unique_name'))

    op.drop_table('project_downloads')
    op.drop_table('feedback_downloads')

    op.drop_table('acr_project')
    op.drop_table('acl_feedback')
    op.drop_table('acr_feedback')
    op.drop_table('acl_project')

    op.drop_table('project_assets')
    op.drop_table('feedback_assets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_project',
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['project_assets.id'], name=op.f('acl_project_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('acl_project_ibfk_2')),
    sa.PrimaryKeyConstraint('asset_id', 'user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('acr_feedback',
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['feedback_assets.id'], name=op.f('acr_feedback_ibfk_1')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('acr_feedback_ibfk_2')),
    sa.PrimaryKeyConstraint('asset_id', 'role_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('feedback_assets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('license_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.Column('mimetype', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True),
    sa.Column('target_name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('unique_name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=False),
    sa.Column('filesize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('unattached', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('bucket', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('encryption', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('encrypted_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nonce', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('compressed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('compressed_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['asset_licenses.id'], name='feedback_assets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('feedback_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('nonce'), ['nonce'], unique=True)
        batch_op.create_index(batch_op.f('ix_feedback_assets_timestamp'), ['timestamp'], unique=False)

    op.create_table('acl_feedback',
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['feedback_assets.id'], name=op.f('acl_feedback_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('acl_feedback_ibfk_2')),
    sa.PrimaryKeyConstraint('asset_id', 'user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('acr_project',
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['project_assets.id'], name=op.f('acr_project_ibfk_1')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('acr_project_ibfk_2')),
    sa.PrimaryKeyConstraint('asset_id', 'role_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('project_downloads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('downloader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['project_assets.id'], name=op.f('project_downloads_ibfk_1')),
    sa.ForeignKeyConstraint(['downloader_id'], ['users.id'], name=op.f('project_downloads_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('project_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_downloads_timestamp'), ['timestamp'], unique=False)

    op.create_table('project_assets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('license_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.Column('mimetype', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True),
    sa.Column('target_name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('unique_name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=255), nullable=False),
    sa.Column('filesize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('unattached', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('bucket', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('encryption', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('encrypted_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nonce', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('compressed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('compressed_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['asset_licenses.id'], name=op.f('project_assets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('project_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_name'), ['unique_name'], unique=True)
        batch_op.create_index(batch_op.f('nonce'), ['nonce'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_assets_timestamp'), ['timestamp'], unique=False)

    op.create_table('feedback_downloads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('downloader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['feedback_assets.id'], name=op.f('feedback_downloads_ibfk_1')),
    sa.ForeignKeyConstraint(['downloader_id'], ['users.id'], name=op.f('feedback_downloads_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('feedback_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_downloads_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###
