"""Add EmailTemplateLabel concept

Revision ID: b4da2ffbe5b3
Revises: 825e7d34b5b9
Create Date: 2026-03-09 21:06:13.510467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4da2ffbe5b3'
down_revision = '825e7d34b5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('colour', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('email_templates_to_labels',
    sa.Column('email_template_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['email_template_labels.id'], ),
    sa.PrimaryKeyConstraint('email_template_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates_to_labels')
    op.drop_table('email_template_labels')
    # ### end Alembic commands ###
