"""Add marking workflow fields to SubmissionRecord

Revision ID: b7422f58ae04
Revises: 041ba8f0b1e9
Create Date: 2025-06-30 12:20:17.023799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7422f58ae04'
down_revision = '041ba8f0b1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Numeric(precision=8, scale=3), nullable=True))
        batch_op.add_column(sa.Column('grade_generated_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_generated_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['grade_generated_id'], ['id'])

        # rename misnamed field
        batch_op.alter_column("exampler_comment", existing_type=sa.Text(), new_column_name="exemplar_comment")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_generated_timestamp')
        batch_op.drop_column('grade_generated_id')
        batch_op.drop_column('grade')

        # restore misnamed field
        batch_op.alter_column("exemplar_comment", existing_type=sa.Text(), new_column_name="exampler_comment")

    # ### end Alembic commands ###
