"""Add fields relating the notifications for SupervisionEvents

Revision ID: bbb4be9402ae
Revises: 9780ff46fbf2
Create Date: 2026-03-14 10:32:24.541512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb4be9402ae'
down_revision = '9780ff46fbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mute', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('prompt_after_event', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('prompt_at_fixed_time', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('prompt_at_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('prompt_in_reminder', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('regular_meeting_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regular_meeting_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('regular_meeting_location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mute', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prompt_sent_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_timestamp')
        batch_op.drop_column('prompt_sent_timestamp')
        batch_op.drop_column('mute')

    with op.batch_alter_table('submission_roles', schema=None) as batch_op:
        batch_op.drop_column('regular_meeting_location')
        batch_op.drop_column('regular_meeting_time')
        batch_op.drop_column('regular_meeting_weekday')
        batch_op.drop_column('prompt_in_reminder')
        batch_op.drop_column('prompt_at_time')
        batch_op.drop_column('prompt_at_fixed_time')
        batch_op.drop_column('prompt_after_event')
        batch_op.drop_column('mute')

    # ### end Alembic commands ###
