"""Add base_id field to MatchingRecord

Revision ID: bf0969529d0c
Revises: 71c0f796b27f
Create Date: 2019-06-03 07:58:24.551651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0969529d0c'
down_revision = '71c0f796b27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('base_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matching_attempts', 'matching_attempts', ['base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matching_attempts', type_='foreignkey')
    op.drop_column('matching_attempts', 'base_id')
    # ### end Alembic commands ###
