"""Add index to state fields in EnrollmentRecord

Revision ID: bf2c30c6a77c
Revises: 7d5e1ea2f69d
Create Date: 2018-09-15 01:44:57.843671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2c30c6a77c'
down_revision = '7d5e1ea2f69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_enrollment_record_marker_state'), 'enrollment_record', ['marker_state'], unique=False)
    op.create_index(op.f('ix_enrollment_record_supervisor_state'), 'enrollment_record', ['supervisor_state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_record_supervisor_state'), table_name='enrollment_record')
    op.drop_index(op.f('ix_enrollment_record_marker_state'), table_name='enrollment_record')
    # ### end Alembic commands ###
