"""Rename user_id field to owner_id in Bookmark

Revision ID: c04b278ed92c
Revises: c63a00b3548f
Create Date: 2018-08-30 23:56:25.684605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c04b278ed92c'
down_revision = 'c63a00b3548f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('bookmarks_ibfk_2', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'selecting_students', ['owner_id'], ['id'])
    op.drop_column('bookmarks', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_ibfk_2', 'bookmarks', 'selecting_students', ['user_id'], ['id'])
    op.drop_column('bookmarks', 'owner_id')
    # ### end Alembic commands ###
