"""Change links between EmailWorkflow models to use direct FK rather than association table

Revision ID: c32126450c1b
Revises: e51968343643
Create Date: 2026-03-24 21:41:23.389361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c32126450c1b'
down_revision = 'e51968343643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_workflow_item_attachment_to_workflow_item')
    op.drop_table('email_workflow_to_items')
    with op.batch_alter_table('email_workflow_item_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'email_workflow_items', ['workflow_item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'email_workflows', ['workflow_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('email_workflow_item_attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workflow_item_id')

    op.create_table('email_workflow_to_items',
    sa.Column('email_workflow_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email_workflow_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_workflow_id'], ['email_workflows.id'], name=op.f('email_workflow_to_items_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_workflow_item_id'], ['email_workflow_items.id'], name=op.f('email_workflow_to_items_ibfk_2'), ondelete='CASCADE'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('email_workflow_item_attachment_to_workflow_item',
    sa.Column('email_workflow_item_attachment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email_workflow_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_workflow_item_attachment_id'], ['email_workflow_item_attachments.id'], name=op.f('email_workflow_item_attachment_to_workflow_item_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_workflow_item_id'], ['email_workflow_items.id'], name=op.f('email_workflow_item_attachment_to_workflow_item_ibfk_2'), ondelete='CASCADE'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
