"""Add encrypted_size and compressed_size fields to asset records

Revision ID: c3437ff8d7d3
Revises: 4aaaaa8f6b48
Create Date: 2023-10-09 08:08:28.677998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3437ff8d7d3'
down_revision = '4aaaaa8f6b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compressed_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compressed_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compressed_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compressed_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('encrypted_size')

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('encrypted_size')

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('encrypted_size')

    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('encrypted_size')

    # ### end Alembic commands ###
