"""Add user sign-off and datestamp flags for confirmation requests

Revision ID: c7f6e38d2f3a
Revises: 281091b6901a
Create Date: 2019-01-20 18:11:47.978372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f6e38d2f3a'
down_revision = '281091b6901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('requests_issued_id', sa.Integer(), nullable=True))
    op.add_column('project_class_config', sa.Column('requests_timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'project_class_config', 'users', ['requests_issued_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_class_config', type_='foreignkey')
    op.drop_column('project_class_config', 'requests_timestamp')
    op.drop_column('project_class_config', 'requests_issued_id')
    # ### end Alembic commands ###
