"""Remove legacy student feedback fields from SubmissionRecord

Revision ID: cd3e98669483
Revises: 44da62fcf652
Create Date: 2026-03-29 11:39:21.671511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd3e98669483'
down_revision = '44da62fcf652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_column('acknowledge_feedback')
        batch_op.drop_column('student_feedback_timestamp')
        batch_op.drop_column('student_feedback')
        batch_op.drop_column('faculty_response_submitted')
        batch_op.drop_column('student_feedback_submitted')
        batch_op.drop_column('faculty_response')
        batch_op.drop_column('faculty_response_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_response_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('faculty_response', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('student_feedback_submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faculty_response_submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_feedback', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('student_feedback_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('acknowledge_feedback', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
