"""Add capacity fields to Project

Revision ID: cd3f85494634
Revises: 2a22b7381836
Create Date: 2018-05-24 17:20:07.403498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3f85494634'
down_revision = '2a22b7381836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('enforce_capacity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'enforce_capacity')
    op.drop_column('projects', 'capacity')
    # ### end Alembic commands ###
