"""Add retired flags to SubmissionRecord and SubmissionPeriodRecord

Revision ID: cff0d0f90e53
Revises: b37862d4934a
Create Date: 2018-09-09 23:00:54.862489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff0d0f90e53'
down_revision = 'b37862d4934a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_selecting_students_retired'), 'selecting_students', ['retired'], unique=False)
    op.add_column('submission_periods', sa.Column('retired', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_submission_periods_retired'), 'submission_periods', ['retired'], unique=False)
    op.create_index(op.f('ix_submission_periods_submission_period'), 'submission_periods', ['submission_period'], unique=False)
    op.add_column('submission_records', sa.Column('retired', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_submission_records_retired'), 'submission_records', ['retired'], unique=False)
    op.create_index(op.f('ix_submission_records_submission_period'), 'submission_records', ['submission_period'], unique=False)
    op.create_index(op.f('ix_submitting_students_retired'), 'submitting_students', ['retired'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitting_students_retired'), table_name='submitting_students')
    op.drop_index(op.f('ix_submission_records_submission_period'), table_name='submission_records')
    op.drop_index(op.f('ix_submission_records_retired'), table_name='submission_records')
    op.drop_column('submission_records', 'retired')
    op.drop_index(op.f('ix_submission_periods_submission_period'), table_name='submission_periods')
    op.drop_index(op.f('ix_submission_periods_retired'), table_name='submission_periods')
    op.drop_column('submission_periods', 'retired')
    op.drop_index(op.f('ix_selecting_students_retired'), table_name='selecting_students')
    # ### end Alembic commands ###
