"""Add remove_on_pageload flag to Notification

Revision ID: d20fc49430f3
Revises: d60c9963767c
Create Date: 2018-06-07 13:43:19.329626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20fc49430f3'
down_revision = 'd60c9963767c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('remove_on_pageload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'remove_on_pageload')
    # ### end Alembic commands ###
