"""Add temporary exam number field to assist with migration to encyrpted field

Revision ID: d29f9c6b3336
Revises: ad841505e2b9
Create Date: 2021-12-08 09:30:32.306180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29f9c6b3336'
down_revision = 'ad841505e2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_data', sa.Column('exam_number_temp', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_data_exam_number_temp'), 'student_data', ['exam_number_temp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_data_exam_number_temp'), table_name='student_data')
    op.drop_column('student_data', 'exam_number_temp')
    # ### end Alembic commands ###
