"""Add associativity table to capture student availability per session

Revision ID: d342ab80c260
Revises: 91aaf1aacbec
Create Date: 2018-11-21 09:54:13.786772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd342ab80c260'
down_revision = '91aaf1aacbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitter_availability',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['presentation_sessions.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['submission_records.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'submitter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitter_availability')
    # ### end Alembic commands ###
