"""Add ProjectHubLayout model

Revision ID: d3da0b21c03e
Revises: 6923193e4023
Create Date: 2020-10-08 11:10:09.468223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3da0b21c03e'
down_revision = '6923193e4023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_hub_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('serialized_layout', sa.String(length=2048, collation='utf8_bin'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['submission_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_hub_layout')
    # ### end Alembic commands ###
