"""refactor bookmark implementation

Revision ID: d485cb36dd1c
Revises: 70aa80e0ad7e
Create Date: 2018-05-21 16:27:28.117625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd485cb36dd1c'
down_revision = '70aa80e0ad7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liveproject_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liveproject_id'], ['live_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['selecting_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_bookmarks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_bookmarks',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['live_projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['selecting_students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'project_id')
    )
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
