"""Add tag field to ScheduleAttempt

Revision ID: d4e38abaf3a0
Revises: 528220252ec6
Create Date: 2019-01-25 16:40:23.114291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4e38abaf3a0'
down_revision = '528220252ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('tag', sa.String(length=255, collation='utf8_bin'), nullable=True))
    op.create_unique_constraint(None, 'scheduling_attempts', ['tag'])
    op.alter_column('users', 'group_summaries',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'summary_frequency',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'summary_frequency',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'group_summaries',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint(None, 'scheduling_attempts', type_='unique')
    op.drop_column('scheduling_attempts', 'tag')
    # ### end Alembic commands ###
