"""Tweaks to database schema for uploaded reports

Revision ID: d53ae3d0a522
Revises: 26a9afb3ba1e
Create Date: 2019-12-19 14:01:45.848655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd53ae3d0a522'
down_revision = '26a9afb3ba1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submission_attachments_ibfk_3', 'submission_attachments', type_='foreignkey')
    op.drop_column('submission_attachments', 'timestamp')
    op.drop_column('submission_attachments', 'uploaded_id')
    op.drop_constraint('submission_records_ibfk_9', 'submission_records', type_='foreignkey')
    op.drop_column('submission_records', 'report_timestamp')
    op.drop_column('submission_records', 'report_uploaded_id')
    op.add_column('submitted_assets', sa.Column('lifetime', sa.Integer(), nullable=True))
    op.add_column('submitted_assets', sa.Column('uploaded_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submitted_assets', 'users', ['uploaded_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submitted_assets', type_='foreignkey')
    op.drop_column('submitted_assets', 'uploaded_id')
    op.drop_column('submitted_assets', 'lifetime')
    op.add_column('submission_records', sa.Column('report_uploaded_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('submission_records', sa.Column('report_timestamp', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('submission_records_ibfk_9', 'submission_records', 'users', ['report_uploaded_id'], ['id'])
    op.add_column('submission_attachments', sa.Column('uploaded_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('submission_attachments', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('submission_attachments_ibfk_3', 'submission_attachments', 'users', ['uploaded_id'], ['id'])
    # ### end Alembic commands ###
