"""Add rank field to MatchingRecord

Revision ID: d5a3ee660533
Revises: 6fb5b8e3bd24
Create Date: 2018-08-22 02:11:34.850509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a3ee660533'
down_revision = '6fb5b8e3bd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matching_id', sa.Integer(), nullable=True),
    sa.Column('selector_id', sa.Integer(), nullable=True),
    sa.Column('submission_period', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['matching_id'], ['matching_attempts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['live_projects.id'], ),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_records')
    # ### end Alembic commands ###
