"""Change some User links to FacultyData

Revision ID: d889466a6ecd
Revises: d3a896489b13
Create Date: 2018-08-22 15:28:05.196258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd889466a6ecd'
down_revision = 'd3a896489b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_config_selectors')
    op.drop_constraint('live_projects_ibfk_3', 'live_projects', type_='foreignkey')
    op.create_foreign_key(None, 'live_projects', 'faculty_data', ['owner_id'], ['id'])
    op.drop_constraint('projects_ibfk_4', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'faculty_data', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_ibfk_4', 'projects', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'live_projects', type_='foreignkey')
    op.create_foreign_key('live_projects_ibfk_3', 'live_projects', 'users', ['owner_id'], ['id'])
    op.create_table('match_config_selectors',
    sa.Column('match_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('selector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matching_attempts.id'], name='match_config_selectors_ibfk_1'),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], name='match_config_selectors_ibfk_2'),
    sa.PrimaryKeyConstraint('match_id', 'selector_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
