"""Add base_bias field to MatchingRecord

Revision ID: d921b21218ef
Revises: bf0969529d0c
Create Date: 2019-06-03 14:27:50.446070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd921b21218ef'
down_revision = 'bf0969529d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_attempts', sa.Column('base_bias', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_attempts', 'base_bias')
    # ### end Alembic commands ###
