"""Adjust models to remove academic years from FHEQ levels

Revision ID: d942317b4714
Revises: a6066e59695f
Create Date: 2022-12-07 16:12:18.581236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd942317b4714'
down_revision = 'a6066e59695f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fheq_levels', sa.Column('numeric_level', sa.Integer(), nullable=True))
    op.drop_index('academic_year', table_name='fheq_levels')
    op.create_unique_constraint(None, 'fheq_levels', ['numeric_level'])
    op.drop_column('fheq_levels', 'academic_year')
    op.add_column('project_classes', sa.Column('start_year', sa.Integer(), nullable=True))
    op.drop_constraint('project_classes_ibfk_5', 'project_classes', type_='foreignkey')
    op.drop_column('project_classes', 'start_level_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('start_level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('project_classes_ibfk_5', 'project_classes', 'fheq_levels', ['start_level_id'], ['id'])
    op.drop_column('project_classes', 'start_year')
    op.add_column('fheq_levels', sa.Column('academic_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fheq_levels', type_='unique')
    op.create_index('academic_year', 'fheq_levels', ['academic_year'], unique=False)
    op.drop_column('fheq_levels', 'numeric_level')
    # ### end Alembic commands ###
