"""Add feedback_open flag to PresentationAssessment

Revision ID: da0f101b7826
Revises: 8ef76755b555
Create Date: 2018-10-24 11:57:08.102016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0f101b7826'
down_revision = '8ef76755b555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_assessments', sa.Column('feedback_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_assessments', 'feedback_open')
    # ### end Alembic commands ###
