"""Add new field in ScheduleAttempt for maximum number of assessor assignments

Revision ID: daf38e019e32
Revises: f5db5c6a377f
Create Date: 2018-11-30 13:00:28.109647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf38e019e32'
down_revision = 'f5db5c6a377f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_attempts', sa.Column('assessor_assigned_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_attempts', 'assessor_assigned_limit')
    # ### end Alembic commands ###
