"""Remove is_template field from FeedbackAsset

Revision ID: dc092f0e28b4
Revises: f5b6c7d8e9a0
Create Date: 2026-04-27 14:55:53.208694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc092f0e28b4'
down_revision = 'f5b6c7d8e9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_assets', schema=None) as batch_op:
        batch_op.drop_column('is_template')

    with op.batch_alter_table('live_marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)
        batch_op.alter_column('rubric',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)
        batch_op.alter_column('schema',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)

    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.alter_column('report',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)

    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)
        batch_op.alter_column('rubric',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)
        batch_op.alter_column('schema',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('schema',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)
        batch_op.alter_column('rubric',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)

    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.alter_column('report',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)

    with op.batch_alter_table('live_marking_schemes', schema=None) as batch_op:
        batch_op.alter_column('schema',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)
        batch_op.alter_column('rubric',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(charset='utf8'),
               nullable=True)

    with op.batch_alter_table('feedback_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
