"""Continue to populate SubmittingStudent

Revision ID: dc5cd0c1ebbe
Revises: e19ff59459cf
Create Date: 2018-09-06 12:02:28.034707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5cd0c1ebbe'
down_revision = 'e19ff59459cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitting_students', sa.Column('matching_record_id', sa.Integer(), nullable=True))
    op.add_column('submitting_students', sa.Column('selector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submitting_students', 'selecting_students', ['selector_id'], ['id'])
    op.create_foreign_key(None, 'submitting_students', 'matching_records', ['matching_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submitting_students', type_='foreignkey')
    op.drop_constraint(None, 'submitting_students', type_='foreignkey')
    op.drop_column('submitting_students', 'selector_id')
    op.drop_column('submitting_students', 'matching_record_id')
    # ### end Alembic commands ###
