"""Add filter state to ProjectClassConfig

Revision ID: e2256c377e32
Revises: f04340e950bf
Create Date: 2018-07-26 10:18:32.179405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2256c377e32'
down_revision = 'f04340e950bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conv_group_filters',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('research_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_groups.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'research_group_id')
    )
    op.create_table('conv_skill_filters',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('skill_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['project_class_config.id'], ),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'skill_group_id')
    )
    op.create_table('sel_group_filters',
    sa.Column('selector_id', sa.Integer(), nullable=False),
    sa.Column('research_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_groups.id'], ),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.PrimaryKeyConstraint('selector_id', 'research_group_id')
    )
    op.create_table('sel_skill_filters',
    sa.Column('selector_id', sa.Integer(), nullable=False),
    sa.Column('skill_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], ),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], ),
    sa.PrimaryKeyConstraint('selector_id', 'skill_group_id')
    )
    op.drop_table('group_filters')
    op.drop_table('skill_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_filters',
    sa.Column('selector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skill_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], name='skill_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_groups.id'], name='skill_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('selector_id', 'skill_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('group_filters',
    sa.Column('selector_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('research_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_groups.id'], name='group_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['selector_id'], ['selecting_students.id'], name='group_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('selector_id', 'research_group_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('sel_skill_filters')
    op.drop_table('sel_group_filters')
    op.drop_table('conv_skill_filters')
    op.drop_table('conv_group_filters')
    # ### end Alembic commands ###
