"""add keywords field to projects

Revision ID: e2cfd0743191
Revises: a7fb8300accf
Create Date: 2018-05-15 13:57:32.991681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cfd0743191'
down_revision = 'a7fb8300accf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('keywords', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'keywords')
    # ### end Alembic commands ###
