"""Add foundation year and year-out flags to DegreeProgramme

Revision ID: e30a2ac6fd71
Revises: 7fc858dfefd2
Create Date: 2020-09-22 15:57:53.111396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30a2ac6fd71'
down_revision = '7fc858dfefd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree_programmes', sa.Column('foundation_year', sa.Boolean(), nullable=True))
    op.add_column('degree_programmes', sa.Column('year_out', sa.Boolean(), nullable=True))
    op.add_column('degree_programmes', sa.Column('year_out_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degree_programmes', 'year_out_value')
    op.drop_column('degree_programmes', 'year_out')
    op.drop_column('degree_programmes', 'foundation_year')
    # ### end Alembic commands ###
