"""Add missing recipients fields in EmailWorkflowItem

Revision ID: e51968343643
Revises: 9ba9c1b9885d
Create Date: 2026-03-24 21:22:19.861490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51968343643'
down_revision = '9ba9c1b9885d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_workflow_to_items',
    sa.Column('email_workflow_id', sa.Integer(), nullable=True),
    sa.Column('email_workflow_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_workflow_id'], ['email_workflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_workflow_item_id'], ['email_workflow_items.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('email_workflow_item_attachment_to_workflow_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_workflow_item_attachment_to_workflow_item_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('email_workflow_item_attachment_to_workflow_item_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_workflow_item_attachments', ['email_workflow_item_attachment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'email_workflow_items', ['email_workflow_item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_list', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('from_email', sa.String(length=255, collation='utf8_bin'), nullable=True))
        batch_op.add_column(sa.Column('reply_to', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_workflow_items', schema=None) as batch_op:
        batch_op.drop_column('reply_to')
        batch_op.drop_column('from_email')
        batch_op.drop_column('recipient_list')

    with op.batch_alter_table('email_workflow_item_attachment_to_workflow_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_workflow_item_attachment_to_workflow_item_ibfk_1'), 'email_workflow_item_attachments', ['email_workflow_item_attachment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('email_workflow_item_attachment_to_workflow_item_ibfk_2'), 'email_workflow_items', ['email_workflow_item_id'], ['id'])

    op.drop_table('email_workflow_to_items')
    # ### end Alembic commands ###
