"""Remove MatchingAttempt field from MainConfig

Revision ID: e5d314386327
Revises: 5ddb7110f47c
Create Date: 2018-09-05 13:11:12.284534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5d314386327'
down_revision = '5ddb7110f47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('main_config_ibfk_1', 'main_config', type_='foreignkey')
    op.drop_column('main_config', 'matching_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_config', sa.Column('matching_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('main_config_ibfk_1', 'main_config', 'matching_attempts', ['matching_id'], ['id'])
    # ### end Alembic commands ###
