"""Add uses_supervisor flag to ProjectClass

Revision ID: e5f72ab6999c
Revises: d342ab80c260
Create Date: 2018-11-21 12:54:55.433628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f72ab6999c'
down_revision = 'd342ab80c260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('uses_supervisor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'uses_supervisor')
    # ### end Alembic commands ###
