"""Move feedback_open flag back to ProjectClassConfig

Revision ID: e664f5131eb2
Revises: 3a1984c3ed4d
Create Date: 2018-09-07 00:45:35.251866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e664f5131eb2'
down_revision = '3a1984c3ed4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_class_config', sa.Column('feedback_open', sa.Boolean(), nullable=True))
    op.drop_column('submission_records', 'feedback_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('feedback_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('project_class_config', 'feedback_open')
    # ### end Alembic commands ###
