"""Add location field to SupervisionEvent

Revision ID: e6fed1a9a06d
Revises: 41c8d57ee973
Create Date: 2026-03-15 01:42:02.297649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fed1a9a06d'
down_revision = '41c8d57ee973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255, collation='utf8_bin'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_events', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
