"""Add foundation year flag in StudentData

Revision ID: e78c36791874
Revises: 32122565686d
Create Date: 2018-08-29 11:47:49.056299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78c36791874'
down_revision = '32122565686d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_data', sa.Column('foundation_year', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_data', 'foundation_year')
    # ### end Alembic commands ###
