"""Add approvals team assocation for ProjectClass

Revision ID: e806dbd2129e
Revises: 9fd0ba938ba4
Create Date: 2022-12-09 10:30:42.428361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e806dbd2129e'
down_revision = '9fd0ba938ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals_team',
    sa.Column('project_class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_class_id'], ['project_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_class_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals_team')
    # ### end Alembic commands ###
