"""Add owner_id to DatabaseSchedulerEntry

Revision ID: edc829d3898c
Revises: 96831a477ec1
Create Date: 2018-06-01 12:18:01.977854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc829d3898c'
down_revision = '96831a477ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_schedules', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'celery_schedules', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'celery_schedules', type_='foreignkey')
    op.drop_column('celery_schedules', 'owner_id')
    # ### end Alembic commands ###
