"""Add use_project_hub flag to SubmissionRecord model

Revision ID: f02f53c30439
Revises: 16c6a7fec835
Create Date: 2021-11-30 22:59:25.471225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02f53c30439'
down_revision = '16c6a7fec835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_records', sa.Column('use_project_hub', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_records', 'use_project_hub')
    # ### end Alembic commands ###
