"""Add default options to FacultyData

Revision ID: f04340e950bf
Revises: 675dafa82779
Create Date: 2018-07-22 21:02:35.930928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04340e950bf'
down_revision = '675dafa82779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_data', sa.Column('CATS_marking', sa.Integer(), nullable=True))
    op.add_column('faculty_data', sa.Column('CATS_supervision', sa.Integer(), nullable=True))
    op.add_column('faculty_data', sa.Column('enforce_capacity', sa.Boolean(), nullable=True))
    op.add_column('faculty_data', sa.Column('project_capacity', sa.Integer(), nullable=True))
    op.add_column('faculty_data', sa.Column('show_popularity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_data', 'show_popularity')
    op.drop_column('faculty_data', 'project_capacity')
    op.drop_column('faculty_data', 'enforce_capacity')
    op.drop_column('faculty_data', 'CATS_supervision')
    op.drop_column('faculty_data', 'CATS_marking')
    # ### end Alembic commands ###
