"""Database changes to support migration to MarkingEvent workflow

Revision ID: f3f7a7b2dd6d
Revises: 64019b166d57
Create Date: 2026-03-25 14:22:56.655175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3f7a7b2dd6d'
down_revision = '64019b166d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.create_unique_constraint(None, ['period_id', 'name'])

    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('marking_workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['event_id', 'name'])
        batch_op.create_foreign_key(None, 'marking_events', ['event_id'], ['id'])

    with op.batch_alter_table('submitter_report_to_feedback_report', schema=None) as batch_op:
        batch_op.alter_column('feedback_report_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'feedback_reports', ['feedback_report_id'], ['id'])

    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Integer(), nullable=False))
        batch_op.alter_column('grade',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'marking_workflows', ['workflow_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('grade',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('submitter_report_to_feedback_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('feedback_report_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('marking_workflows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('marking_reports', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('marking_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
