"""Add secondary association table for backup labels

Revision ID: f460bfabbb66
Revises: 823021d1bca4
Create Date: 2023-10-10 07:57:32.460443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f460bfabbb66'
down_revision = '823021d1bca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups_to_labels',
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['backup_labels.id'], ),
    sa.PrimaryKeyConstraint('backup_id', 'label_id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_validated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_column('last_validated')

    op.drop_table('backups_to_labels')
    # ### end Alembic commands ###
