"""Remove unneeded association table

Revision ID: f5db5c6a377f
Revises: 77cd62a460e2
Create Date: 2018-11-30 10:06:53.430113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5db5c6a377f'
down_revision = '77cd62a460e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_availability_waiting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_availability_waiting',
    sa.Column('assessment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('faculty_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['presentation_assessments.id'], name='faculty_availability_waiting_ibfk_1'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_data.id'], name='faculty_availability_waiting_ibfk_2'),
    sa.PrimaryKeyConstraint('assessment_id', 'faculty_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
