"""Add fields to ProjectClass

Revision ID: f6bbf7f81969
Revises: 3ba3e048e3eb
Create Date: 2018-05-17 12:50:25.037626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bbf7f81969'
down_revision = '3ba3e048e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('extent', sa.Integer(), nullable=True))
    op.add_column('project_classes', sa.Column('require_confirm', sa.Boolean(), nullable=True))
    op.add_column('project_classes', sa.Column('supervisor_carryover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'supervisor_carryover')
    op.drop_column('project_classes', 'require_confirm')
    op.drop_column('project_classes', 'extent')
    # ### end Alembic commands ###
