"""Add 'aims' and 'review only' fields to project models

Revision ID: f7046aca3427
Revises: 5d1e15e15471
Create Date: 2019-09-23 14:01:03.045308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7046aca3427'
down_revision = '5d1e15e15471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptions', sa.Column('aims', sa.Text(), nullable=True))
    op.add_column('descriptions', sa.Column('review_only', sa.Boolean(), nullable=True))
    op.add_column('live_projects', sa.Column('aims', sa.Text(), nullable=True))
    op.add_column('live_projects', sa.Column('review_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_projects', 'review_only')
    op.drop_column('live_projects', 'aims')
    op.drop_column('descriptions', 'review_only')
    op.drop_column('descriptions', 'aims')
    # ### end Alembic commands ###
