"""Add further fields to MarkingEvent and dependent models

Revision ID: f89922179f9b
Revises: 7fb3f39a90b3
Create Date: 2026-03-26 10:04:09.606629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89922179f9b'
down_revision = '7fb3f39a90b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_on_moderation_required',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marking_workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marking_workflow_id'], ['marking_workflows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'marking_workflow_id')
    )
    op.create_table('notify_on_validation_failure',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marking_workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marking_workflow_id'], ['marking_workflows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'marking_workflow_id')
    )
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_state', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitter_reports', schema=None) as batch_op:
        batch_op.drop_column('workflow_state')

    op.drop_table('notify_on_validation_failure')
    op.drop_table('notify_on_moderation_required')
    # ### end Alembic commands ###
