"""Add display_marker and display_presentations fields to ProjectClass

Revision ID: f8b116a12922
Revises: 6923193e4023
Create Date: 2020-11-05 14:50:00.092281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b116a12922'
down_revision = '6923193e4023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_classes', sa.Column('display_marker', sa.Boolean(), nullable=True))
    op.add_column('project_classes', sa.Column('display_presentations', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_classes', 'display_presentations')
    op.drop_column('project_classes', 'display_marker')
    # ### end Alembic commands ###
