"""Rename PresentationSession.label to .name

Revision ID: f8f78799a225
Revises: f6af1fdee2ea
Create Date: 2026-01-21 20:31:01.106950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f78799a225'
down_revision = 'f6af1fdee2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentation_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255, collation='utf8_bin'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentation_sessions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
