"""Add filesize field to asset records

Revision ID: fa22c08aa8a7
Revises: 98eb265f0289
Create Date: 2023-05-19 14:33:59.881980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa22c08aa8a7'
down_revision = '98eb265f0289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))

    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_assets', schema=None) as batch_op:
        batch_op.drop_column('filesize')

    with op.batch_alter_table('submitted_assets', schema=None) as batch_op:
        batch_op.drop_column('filesize')

    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.drop_column('filesize')

    # ### end Alembic commands ###
