"""Add missing year fields to workflow history records

Revision ID: fb1c84380a2f
Revises: 34dd50ad50c8
Create Date: 2019-03-16 17:53:19.900758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1c84380a2f'
down_revision = '34dd50ad50c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_project', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow_project', 'main_config', ['year'], ['year'])
    op.add_column('workflow_studentdata', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow_studentdata', 'main_config', ['year'], ['year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_studentdata', type_='foreignkey')
    op.drop_column('workflow_studentdata', 'year')
    op.drop_constraint(None, 'workflow_project', type_='foreignkey')
    op.drop_column('workflow_project', 'year')
    # ### end Alembic commands ###
