"""Add PresentationFeedback model

Revision ID: fdfb22e562af
Revises: 0a059a3897b5
Create Date: 2018-10-23 12:01:47.899449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfb22e562af'
down_revision = '0a059a3897b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('assessor_id', sa.Integer(), nullable=True),
    sa.Column('presentation_positive', sa.Text(), nullable=True),
    sa.Column('presentation_negative', sa.Text(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessor_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['submission_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presentation_feedback')
    # ### end Alembic commands ###
