"""Remove feedback_open flag from PresentationAssessment

Revision ID: fdfcff467a19
Revises: f1224b802630
Create Date: 2026-03-24 09:41:17.428248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdfcff467a19'
down_revision = 'f1224b802630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presentation_feedback')
    with op.batch_alter_table('presentation_assessments', schema=None) as batch_op:
        batch_op.drop_column('feedback_open')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentation_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    op.create_table('presentation_feedback',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assessor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('negative', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('positive', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.CheckConstraint('`submitted` in (0,1)', name=op.f('CONSTRAINT_1')),
    sa.ForeignKeyConstraint(['assessor_id'], ['faculty_data.id'], name=op.f('presentation_feedback_ibfk_1')),
    sa.ForeignKeyConstraint(['owner_id'], ['submission_records.id'], name=op.f('presentation_feedback_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
