"""Remove unneeded nullable constraints

Revision ID: fe97dbb04366
Revises: 6ee0b913d186
Create Date: 2019-12-22 01:50:08.949653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe97dbb04366'
down_revision = '6ee0b913d186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('period_attachments', 'attachment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('submission_attachments', 'attachment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('period_attachments', 'attachment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('submission_attachments', 'attachment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
