"""Move max_group+_size to SubmissionPeriodRecord

Revision ID: fec1c69a1488
Revises: cacc59a8520c
Create Date: 2018-12-12 15:46:00.257011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fec1c69a1488'
down_revision = 'cacc59a8520c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_definitions', sa.Column('max_group_size', sa.Integer(), nullable=True))
    op.drop_column('scheduling_attempts', 'max_group_size')
    op.add_column('submission_periods', sa.Column('max_group_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_periods', 'max_group_size')
    op.add_column('scheduling_attempts', sa.Column('max_group_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('period_definitions', 'max_group_size')
    # ### end Alembic commands ###
