apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb-data
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ds283/Documents/Code/MPS-Project/mysql/data"
    type: Directory
