apiVersion: appcat.vshn.io/v1
kind: ObjectBucket
metadata:
  name: enginfprojects-initdb-prod
  namespace: suex-enginfprojects-prod
spec:
  parameters:
    bucketName: enginfprojects-initdb-prod
    region: ch-gva-2
    bucketDeletionPolicy: DeleteIfEmpty
  writeConnectionSecretToRef:
    name: enginfprojects-initdb-prod-credentials
