apiVersion: appcat.vshn.io/v1
kind: ObjectBucket
metadata:
  name: enginfprojects-k8up-backup-prod
  namespace: suex-enginfprojects-prod
spec:
  parameters:
    bucketName: enginfprojects-k8up-backup-prod
    region: ch-dk-2
  writeConnectionSecretToRef:
    name: enginfprojects-k8up-backup-prod-credentials
