apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enginfprojects
  namespace: suex-enginfprojects-acpt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enginfprojects
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
