apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: default-worker
  namespace: suex-enginfprojects-acpt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: default-worker
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
