apiVersion: apps/v1
kind: Deployment
metadata:
  name: priority-worker
  namespace: suex-enginfprojects-acpt
  labels:
    app.kubernetes.io/name: priority-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: priority-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: priority-worker
    spec:
      containers:
        - name: mpsproject
          image: quay.io/ds283/mpsproject:latest
          imagePullPolicy: Always
          command: ["./launch_celery.sh"]
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          envFrom:
            - configMapRef:
                name: configmap-environment
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_password
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: root_password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: database
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: username
            - name: MAIL_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: mail-admin
                  key: default_email
            - name: ROLLBAR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rollbar-credentials
                  key: token
            - name: ROLLBAR_ENV
              valueFrom:
                secretKeyRef:
                  name: rollbar-credentials
                  key: environment
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: secret_key
            - name: FLASK_SECURITY_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: password_salt
            - name: SQLALCHEMY_AES_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: sqlalchemy_key
            - name: PROFILER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: profiler_username
            - name: PROFILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: profiler_password
            - name: OBJECT_STORAGE_ASSETS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: objectstore-assets-secrets
                  key: access_key
            - name: OBJECT_STORAGE_ASSETS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: objectstore-assets-secrets
                  key: secret_key
            - name: OBJECT_STORAGE_BACKUP_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: objectstore-backup-secrets
                  key: access_key
            - name: OBJECT_STORAGE_BACKUP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: objectstore-backup-secrets
                  key: secret_key
            - name: WORKER_QUEUES
              value: priority
            - name: DATABASE_URL
              value: mysql+pymysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOSTNAME)/$(DATABASE_NAME)
            - name: CELERY_RESULT_BACKEND
              value: redis://$(REDIS_HOSTNAME):6379
            - name: CELERY_BROKER_URL
              value: redis://$(REDIS_HOSTNAME):6379
            - name: CACHE_REDIS_URL
              value: redis://$(REDIS_HOSTNAME):6379
            - name: RATELIMIT_REDIS_URI
              value: redis://$(REDIS_HOSTNAME):6379
            - name: SESSION_MONGO_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOSTNAME):27017
            - name: PROFILER_MONGO_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOSTNAME):27017
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: local-config
              mountPath: /mpsproject/app/instance/local.py
              subPath: local.py
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: local-config
          configMap:
            name: configmap-local
      restartPolicy: Always
