apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: suex-enginfprojects-acpt
  labels:
    app.kubernetes.io/name: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
  ports:
    - port: 6379
