apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      restartPolicy: Always
