apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.2"
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: database
          volumeMounts:
            - mountPath: /data/models
              name: mount-mongodb-data
      volumes:
        - name: mount-mongodb-data
          persistentVolumeClaim:
            claimName: pvc-mongodb-data
      restartPolicy: Always
