apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-scheduler
  labels:
    app.kubernetes.io/name: celery-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celery-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: celery-scheduler
    spec:
      containers:
        - name: webapp
          image: mpsproject/webapp:latest
          imagePullPolicy: IfNotPresent
          command: ["./launch_beat.sh"]
          resources:
            requests:
              cpu: "0.1"
          env:
            - name: REDIS_HOSTNAME
              value: redis
            - name: MONGODB_HOSTNAME
              value: mongodb
            - name: DATABASE_HOSTNAME
              value: mariadb
            - name: CELERY_RESULT_BACKEND
              value: redis://$(REDIS_HOSTNAME):6379
            - name: CELERY_BROKER_URL
              value: redis://$(REDIS_HOSTNAME):6379
            - name: CACHE_REDIS_URL
              value: redis://$(REDIS_HOSTNAME):6379
            - name: RATELIMIT_REDIS_URI
              value: redis://$(REDIS_HOSTNAME):6379
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: database
            - name: DATABASE_URL
              value: mysql+pymysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOSTNAME)/$(DATABASE_NAME)
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root_password
            - name: SESSION_MONGO_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOSTNAME):27017
            - name: INSTANCE_FOLDER
              value: /instance
            - name: OBJECT_STORAGE_ASSETS_URI
              value: gs://mpsprojects-physics-assets
            - name: OBJECT_STORAGE_BACKUP_URI
              value: gs://mpsprojects-physics-backup
            - name: OBJECT_STORAGE_SERVICE_ACCOUNT_FILE
              value: /instance/mpsprojects-physics-cf4adebe8529.json
            - name: PROFILER_MONGO_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOSTNAME):27017
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /instance
              name: mount-instance
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: mount-instance
          persistentVolumeClaim:
            claimName: pvc-instance
      restartPolicy: Always
