apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backups
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/ds283/Documents/Code/MPS-Project/backups"
    type: Directory
