apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb-conf
  labels:
    type: local
spec:
  capacity:
    storage: 10M
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/ds283/Documents/Code/MPS-Project/mysql/conf.d"
    type: Directory
