apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-data
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ds283/Documents/Code/MPS-Project/mongodb"
    type: Directory
