apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-object-store
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/ds283/Documents/Code/MPS-Project/object_storage"
    type: Directory
