apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeName: pv-logs
