apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-profiling
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: pv-profiling
