apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-assets
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: pv-assets
