apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backups
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeName: pv-backups
