apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-object-store
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeName: pv-object-store
