apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-conf
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 10M
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  volumeName: pv-mariadb-conf
