apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-data
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: pv-mongodb-data
