apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  selector:
    app.kubernetes.io/name: mongodb
  type: ClusterIP
  ports:
    - port: 27017
